'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Complete translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation Sidebar
    'nav.overview': 'Overview',
    'nav.markets': 'Markets',
    'nav.opportunities': 'Opportunities',
    'nav.trades': 'Ledger',
    'nav.wallets': 'Reserves',
    'nav.risk': 'Risk Control',
    'nav.health': 'Telemetry',
    'nav.docs': 'Documentation',
    'nav.changelog': 'Build Notes',
    'nav.status': 'NODE STATUS:',
    'nav.live': 'LIVE',
    'nav.toggle_menu': 'Toggle menu',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.sim_only': 'Live Testnet Environment',
    'footer.secure_node': 'SECURE NODE',
    
    // Header Ticker
    'ticker.btc_spot': 'BTC SPOT:',
    'ticker.detection': 'DETECTION:',
    'ticker.p99': 'P99 COMPUTE:',
    'ticker.feeds': 'FEEDS:',
    'ticker.feeds_suffix': 'live',
    'ticker.sim_equity': 'EQUITY:',
    'ticker.streaming': '● STREAMING',
    'ticker.connecting': '○ CONNECTING',
    
    // Overview Dashboard
    'overview.title': 'Quantitative Valuation Console',
    'overview.subtitle': 'Real-time L2 multi-venue valuation engine and execution engine.',
    'overview.total_profit': 'Net P&L',
    'overview.win_rate': 'Win Rate',
    'overview.sharpe': 'Sharpe',
    'overview.mean_latency': 'Mean Compute',
    'overview.p99_latency': 'p99 Compute',
    'overview.books_sec': 'Throughput (Books/sec)',
    'overview.books_processed': 'Total Books Evaluated',
    'overview.opps_detected': 'Opps Detected',
    'overview.pnl_growth': 'Cumulative Equity Curve (100k USD Base)',
    'overview.recent_trades': 'Recent Executions',
    'overview.recent_opps': 'Arbitrage Spread Feed',
    'overview.no_trades': 'Awaiting profitable spreads. Execution triggers automatically.',
    'overview.no_opps': 'Reconciling live WebSocket feeds from connected venues...',
    'overview.pnl_chart': 'CUMULATIVE P&L',
    'overview.under_cooldown': 'Risk Breaker Active - Cooldown Mode',
    'overview.monitor_btn': 'Order Books',
    'overview.risk_btn': 'Risk Settings',
    'overview.portfolio_equity': 'PORTFOLIO EQUITY',
    'overview.initial_reserve': '100k USD Initial Allocation',
    'overview.sim_net_pnl': 'LIVE NET P&L',
    'overview.after_slippage_fees': 'Net of Slippage & Fees',
    'overview.win_rate_label': 'WIN RATE',
    'overview.win_rate_sub': 'Slippage loss checks armed',
    'overview.total_trades': 'TOTAL TRADES',
    'overview.avg_trade_prefix': 'Avg:',
    'overview.avg_trade_suffix': '/ trade',
    'overview.sharpe_ratio': 'RATIO SHARPE',
    'overview.sharpe_sub': 'Risk-free rate: 0.0%',
    'overview.sharpe_building': 'Calculating',
    'overview.compute': 'compute',
    'overview.detection_latency': 'DETECTION LATENCY',
    'overview.books': 'books',
    'overview.windows': 'windows',
    'overview.pnl_chart_title': 'Cumulative P&L',
    'overview.pnl_chart_sub': 'Live block-by-block execution equity curve',
    'overview.real_time': 'REAL-TIME',
    'overview.sim_context': 'Execution Context',
    'overview.core_algorithm': 'CORE VALUATION LOOP:',
    'overview.core_algorithm_desc': 'Scans all directed pairs across 5 live exchanges (Binance, Kraken, Coinbase, OKX, Bybit). Sizes executions via L2 depth-walking and verifies net spreads after CEX taker fees, slippage cushions, stablecoin basis costs, and network delays.',
    'overview.sim_rules': 'EXECUTION RULES:',
    'overview.sim_rules_desc': 'Trades are executed on testnet. Wallet balances auto-reset when limits are reached or capital drops below baseline thresholds.',
    'overview.last_update': 'Last Update:',
    'overview.awaiting_data': 'Awaiting telemetry...',
    'overview.recent_executions': 'Recent Executions',
    'overview.trade_ledger_sub': 'Audit ledger logs',
    'overview.view_all_btn': 'Open Ledger Logs →',
    'overview.awaiting_trades': 'Awaiting profitable spreads. Adjust risk thresholds in settings to widen capture bands.',
    
    // Triangular Arbitrage panel
    'tri.title': 'Triangular Arbitrage',
    'tri.subtitle': 'Binance Spot Cycle: USDT · BTC · ETH',
    'tri.unavailable': 'Awaiting Binance ETH legs...',
    'tri.gross_edge': 'Gross Edge',
    'tri.fee_cost': 'Fee Drag (3 Legs)',
    'tri.net_edge': 'Net Edge',
    'tri.notional': 'Notional',
    'tri.exp_profit': 'Expected Margin',
    'tri.executed': 'Cycles Run',
    'tri.profitable': 'Profitable',
    'tri.below_floor': 'Below Fee Floor',

    // Home Hero & Intro
    'home.hero_subtitle': 'Real-time Bitcoin cross-exchange arbitrage engine',
    'home.metric_venues': '5 Connected Venues',
    'home.metric_books': 'Live L2 Depth',
    'home.metric_execution': 'Testnet Execution',
    'home.metric_strategy': 'Cross-Exchange + Triangular',
    'home.cta_opportunities': 'Arbitrage Feed',
    'home.cta_trades': 'Trade Ledger',
    'home.inst_bullet1_title': 'Market Data Feeds',
    'home.inst_bullet1_desc': 'Low-latency public market book snapshots streamed via WebSockets.',
    'home.inst_bullet2_title': 'Spread Math Hedges',
    'home.inst_bullet2_desc': 'Net profitability scaled against L2 depth, fees, slippage, and adverse price drift.',
    'home.inst_bullet3_title': 'Reserve Tracking',
    'home.inst_bullet3_desc': 'Real-time balance reconciliation, automated wallet routing, and persistent execution ledger.',

    // Table Headers
    'table.timestamp': 'TIMESTAMP',
    'table.route': 'ROUTE',
    'table.volume': 'VOLUME',
    'table.buy_price': 'BUY PRICE',
    'table.sell_price': 'SELL PRICE',
    'table.gross_pnl': 'GROSS P&L',
    'table.net_pnl': 'NET P&L',

    // Comparative Markets
    'markets.title': 'Comparative L2 Markets',
    'markets.subtitle': 'Real-time L2 depth synchronization and side-by-side liquidity tracking.',
    'markets.exchange_label': 'Exchange Platform',
    'markets.symbol_label': 'Trading Pair Symbol',
    'markets.top_bids': 'Top Bids (Buyers)',
    'markets.top_asks': 'Top Asks (Sellers)',
    'markets.price': 'Price (USD)',
    'markets.size': 'Size (BTC)',
    'markets.total': 'Total',
    'markets.no_depth': 'Connecting WebSocket stream...',
    'markets.depth_visualizer': 'L2 Order Book Depth Visualization (BTC/USDT)',
    'markets.route_permutation': 'ROUTE PERMUTATION',
    'markets.arb_window': 'ARBITRAGE WINDOW',
    'markets.no_spread': 'NO SPREAD',
    'markets.gross_spread': 'GROSS SPREAD',
    'markets.est_fees': 'COMMISSIONS & SLIPPAGE',
    'markets.net_estimate': 'NET ESTIMATE',
    'markets.unprofitable': 'UNPROFITABLE',
    'markets.liquidity_title': 'Liquidity Depth Analysis',
    'markets.liquidity_sub': 'Cumulative volume meeting at mid-price',
    'markets.awaiting_books': 'Synchronizing WebSocket order books...',
    'markets.binance_l2': 'Binance Spot L2 (BTC/USDT)',
    'markets.kraken_l2': 'Kraken Spot L2 (XBT/USD)',
    'markets.binance_l2_desc': 'Taker Fee: 0.04% | 100ms Updates',
    'markets.kraken_l2_desc': 'Taker Fee: 0.10% | CRC32 Checksums Active',
    'markets.mid_price': 'MID PRICE',
    'markets.bids_buy': 'Bids (Buy)',
    'markets.asks_sell': 'Asks (Sell)',
    'markets.awaiting_ws': 'Awaiting WebSocket...',
    'markets.reference_aggregators': 'Reference Aggregators',
    'markets.reference_desc': 'Cross-check live spot spreads and liquidity volume against global reference platforms.',

    // Live Opportunities
    'opps.title': 'Arbitrage Spreads Log',
    'opps.subtitle': 'Real-time valuation feed of candidate spreads filtered by risk parameters.',
    'opps.filter_all': 'All Spreads',
    'opps.filter_executed': 'Executed',
    'opps.filter_skipped': 'Skipped',
    'opps.col_time': 'Detected At',
    'opps.col_pair': 'Venue Transition',
    'opps.col_gross': 'Gross Spread',
    'opps.col_net': 'Net Spread',
    'opps.col_volume': 'Max Volume',
    'opps.col_profit': 'Exp. Profit',
    'opps.col_confidence': 'Conf. (σ)',
    'opps.col_status': 'Status',
    'opps.col_reason': 'Action / Reason',
    'opps.executed': 'EXECUTED',
    'opps.skipped': 'SKIPPED',
    'opps.no_opps': 'No spreads evaluated yet. Ingesting WS streams...',
    'opps.title_header': 'Live Arbitrage Opportunities',
    'opps.subtitle_header': 'Real-time valuation feed of candidate spreads filtered by risk parameters.',
    'opps.filter_all_label': 'All Feeds',
    'opps.filter_executed_label': 'Executed',
    'opps.filter_skipped_label': 'Skipped',
    'opps.col_ask_buy': 'ASK (BUY)',
    'opps.col_bid_sell': 'BID (SELL)',
    'opps.no_opps_filter': 'No spreads found matching active filter.',
    'opps.success_reason': 'Sized and Executed Successfully',
    'opps.table_sub': 'Derived from order book snapshots',
    'opps.zscore_tooltip': "Statistical confidence: spread z-score vs rolling history. Higher values signal statistical mean-reversion.",

    // Executed Trades
    'trades.title': 'Executed Trades Ledger',
    'trades.subtitle': 'Testnet executions respecting walked L2 liquidity, spot slippage, and taker fees.',
    'trades.export': 'Export Ledger (CSV)',
    'trades.col_time': 'Executed At',
    'trades.col_id': 'Transaction ID',
    'trades.col_venues': 'Direction',
    'trades.col_buy_price': 'Buy Price (VWAP)',
    'trades.col_sell_price': 'Sell Price (VWAP)',
    'trades.col_volume': 'Volume (BTC)',
    'trades.col_gross': 'Gross P&L',
    'trades.col_fees': 'Taker Fees',
    'trades.col_slippage': 'Slippage',
    'trades.col_net': 'Net Profit',
    'trades.no_trades': 'No testnet transactions executed yet. Curves update on fill.',
    'trades.title_header': 'Live Trade Ledger',
    'trades.subtitle_header': 'Audit logs of all completed, cost-hedged arbitrage executions.',
    'trades.export_btn': 'Export CSV',
    'trades.accumulated_pnl': 'CUMULATIVE NET P&L',
    'trades.win_rate_count': 'WIN RATE / TOTAL',
    'trades.total_fees': 'TOTAL TAKER FEES',
    'trades.slippage_loss': 'SLIPPAGE DRAG',
    'trades.table_title': 'Trade Ledger',
    'trades.table_sub': 'Execution logs',
    'trades.no_trades_message': 'No executions yet. Awaiting spreads that clear fully-loaded operational costs.',

    // Live Wallets
    'wallets.title': 'Capital Allocations',
    'wallets.subtitle': 'Saldos en vivo en tiempo real. Los fondos se rebalancean automáticamente al capturar spreads.',
    'wallets.exchange': 'Exchange Venue',
    'wallets.asset': 'Asset',
    'wallets.free': 'Free Amount',
    'wallets.locked': 'Locked Amount',
    'wallets.total': 'Total Balance',
    'wallets.value_usd': 'Approx Value (USD)',
    'wallets.reset_btn': 'Reset Wallet Pools',
    'wallets.reset_warning': 'This resets all exchange allocations to initial values.',
    'wallets.title_header': 'Live Capital Reserves',
    'wallets.subtitle_header': 'Real-time liquidity reserves, asset splits, and net exposure profiles.',
    'wallets.pool_title': 'Balance Pool',
    'wallets.active_reserve': 'ACTIVE RESERVE',
    'wallets.free_label': 'Free',
    'wallets.locked_label': 'Locked',
    'wallets.oversight_title': 'Asset Allocation Oversight',
    'wallets.agg_btc': 'AGGREGATE BTC SPOT EXPOSURE:',
    'wallets.agg_quote': 'AGGREGATE QUOTE CASH EXPOSURE:',

    // Risk & Settings
    'risk.title': 'Risk Oversight Console',
    'risk.subtitle': 'Calibrate spreads, configure circuit breakers, and enforce exposure limits.',
    'risk.circuit_breakers': 'System Circuit Breakers',
    'risk.cooldown_status': 'Circuit status',
    'risk.cooldown_active': 'ACTIVE COOLDOWN (ENGINE FROZEN)',
    'risk.cooldown_inactive': 'NOMINAL (RUNNING)',
    'risk.exchanges_exposure': 'Exposure Controls',
    'risk.global_btc': 'Global BTC Exposure Cap',
    'risk.global_quote': 'Global Quote Exposure Cap',
    'risk.losses_limit': 'Consecutive Losses Breaker',
    'risk.volatility_breaker': 'Volatility Crash Safeguard',
    'risk.volatility_limit': 'Max Price Divergence',
    'risk.settings_form': 'Calibration Panel',
    'risk.min_net_profit': 'Min Net Profit (USD)',
    'risk.max_btc_per_cex': 'Max BTC allocation per CEX',
    'risk.max_quote_per_cex': 'Max quote allocation per CEX',
    'risk.latency_bps': 'Latency Drift Buffer (BPS)',
    'risk.slippage_bps': 'Slippage Cushion (BPS)',
    'risk.trades_per_min': 'Max Trade Speed (per min)',
    'risk.save_btn': 'Persist Configuration',
    'risk.pass_placeholder': 'Enter API secret key...',
    'risk.success_save': 'Configuration updated and persisted.',
    'risk.error_save': 'Failed to update. Check API secret key.',
    'risk.cooldown_reason': 'Breaker Tripped: Incurred 3 consecutive trade losses from synthetic market slippage.',
    'risk.title_header': 'Risk Oversight Console',
    'risk.subtitle_header': 'Calibrate spreads, configure circuit breakers, and enforce exposure limits.',
    'risk.system_breaker': 'SYSTEM CIRCUIT BREAKER',
    'risk.engine_health': 'RISK ENGINE SYSTEM HEALTH',
    'risk.circuit_status': 'CIRCUIT STATUS',
    'risk.default_reason': 'All parameters operating within nominal bounds.',
    'risk.consecutive_losses': 'CONSECUTIVE LOSSES',
    'risk.cooldown_timer': 'COOLDOWN TIMER',
    'risk.seconds_remaining': 's remaining',
    'risk.inactive': 'INACTIVE',
    'risk.emergency_ops': 'Emergency Operations',
    'risk.rebalance_title': 'Reset Wallet Pools',
    'risk.rebalance_desc': 'Wipes transaction logs, opportunities, and ledger databases, restoring wallets to defaults.',
    'risk.resetting_btn': 'Resetting...',
    'risk.reset_balances_btn': 'RESET WALLET BALANCES',
    'risk.settings_title': 'Risk Parameters',
    'risk.settings_desc': 'Calibrate mathematical L2 depth-walk and fee/latency hedges.',
    'risk.min_profit_title': 'Minimum Net Profit',
    'risk.min_profit_desc': 'Spread threshold required to trigger testnet orders',
    'risk.max_alloc_title': 'Max Transaction Ceiling',
    'risk.max_alloc_desc': 'Exposure roof capping single transaction sizes',
    'risk.latency_title': 'Latency Drift Buffer',
    'risk.latency_desc': '1 BPS = 0.01%. Expected profit buffer for WebSocket lag rejections',
    'risk.slippage_title': 'Slippage Safety Cushion',
    'risk.slippage_desc': 'Extra safety buffer used to deduct testnet fill prices',
    'risk.exec_latency_title': 'Execution Latency',
    'risk.exec_latency_desc': 'Modeled order-to-fill latency. Price drift over this window aborts orders if the edge vanishes.',
    'risk.pause_aria': 'Toggle emergency pause',
    'risk.saving_msg': 'Saving...',
    'risk.success_msg': '✅ Configuration persisted successfully.',
    'risk.error_msg': '❌ Failed to save backend configuration.',
    'risk.save_config_btn': 'Save Settings',
    'risk.persisting_btn': 'Persisting...',
    'risk.dialog_title': 'Reset Testnet State',
    'risk.dialog_desc': 'WARNING: This will wipe all transaction history, opportunities, and log databases, resetting exchange wallet assets back to baseline allocations.',
    'risk.dialog_body': 'This action clears testnet ledger data and restores baseline allocations. This action is irreversible.',
    'risk.cancel': 'Cancel',
    'risk.confirm_reset': 'Confirm Reset',
    'risk.alert_success': '🔄 Testnet database reset successfully.',
    'risk.alert_error': '❌ Failed to complete database reset.',

    // System Health
    'health.title': 'System Feeds & Health',
    'health.subtitle': 'Real-time WebSocket feed status, latencies, CEX ping-pongs, and connection trackers.',
    'health.connection_channels': 'WebSocket Connection Channels',
    'health.venue': 'Exchange Venue',
    'health.stream_url': 'WebSocket Stream Endpoint',
    'health.status_col': 'Channel Status',
    'health.reconnects': 'Reconnects',
    'health.last_msg': 'Last Heartbeat Received',
    'health.system_metrics': 'Live Engine Core Metrics',
    'health.uptime': 'Backend Node Uptime',
    'health.api_endpoints': 'REST JSON API Status & Testing',
    'health.title_header': 'System Health Telemetry',
    'health.subtitle_header': 'Real-time WebSocket monitoring, keepalive tracking, and platform system audit logs.',
    'health.feed_suffix': 'Feed',
    'health.connected': 'CONNECTED',
    'health.disconnected': 'DISCONNECTED',
    'health.reconnect_counter': 'RECONNECT COUNTER:',
    'health.last_heartbeat': 'LAST HEARTBEAT:',
    'health.no_messages': 'No messages',
    'health.terminal_uptime': 'TERMINAL UPTIME',
    'health.client_socket': 'CLIENT SOCKET CONNECT',
    'health.socket_stable': 'STABLE',
    'health.socket_connecting': 'CONNECTING...',
    'health.logged_events': 'LOGGED EVENTS',
    'health.records_label': 'records',
    'health.detection_latency': 'DETECTION LATENCY',
    'health.wire_label': 'wire',
    'health.compute_label': 'compute',
    'health.engine_status': 'ENGINE STATUS',
    'health.engine_live': 'LIVE · TRADING',
    'health.engine_paused': 'PAUSED',
    'health.engine_idle': 'IDLE · NO RECENT EVALS',
    'health.last_activity': 'LAST EVALUATION',
    'health.self_heals': 'SELF-HEALS',
    'health.fill_aborts': 'FILL ABORTS',
    'health.fill_window': 'fill window',
    'health.audit_trails': 'Platform Audit Trails',
    'health.timestamp_col': 'TIMESTAMP',
    'health.type_col': 'TYPE',
    'health.desc_col': 'EVENT LOG DESCRIPTION MESSAGE',
    'health.no_events': 'No system log events recorded yet.',

    // Platform Docs
    'docs.title_header': 'Platform Documentation',
    'docs.subtitle_header': 'Technical reference, execution mechanics, and monorepo topology.',
    'docs.flow_market_data': 'Market Data',
    'docs.flow_opportunity': 'Opportunity Engine',
    'docs.flow_execution': 'Testnet Execution Engine',
    'docs.flow_pnl': 'PnL Tracking',
    'docs.sec1_title': 'Cross-Exchange Arbitrage',
    'docs.sec1_p1': 'Aurex is an institutional-grade, real-time cross-exchange arbitrage engine. It aggregates live L2 order book depth across five centralized venues to calculate, rank, and execute of spreads net of trading fees, slippage, and transport delay.',
    'docs.sec2_title': 'Execution Logic',
    'docs.sec2_p1': 'The engine depth-walks L2 books to determine executable prices, mapping real liquidity constraints to avoid paper-profit calculations.',
    'docs.sec2_seq_title': 'Valuation sequence',
    'docs.sec2_card_step1': 'Initialize with baseline conservative volume.',
    'docs.sec2_card_step2': 'Walk cheap-venue asks and expensive-venue bids.',
    'docs.sec2_card_step3': 'Calculate Volume-Weighted Average Prices (VWAP) from depth.',
    'docs.sec2_card_step4': 'Deduct exchange fees, latency basis buffers, and slippage.',
    'docs.sec2_card_step5': 'Maximize net yield via iterative volume expansion.',
    'docs.sec3_title': 'Cost Framework',
    'docs.sec3_p1': 'Spreads are evaluated net of exchange fees, slippage, latency buffers, and stablecoin USD/USDT conversion costs.',
    'docs.sec3_costs_title': 'Deducted Costs',
    'docs.sec3_li1': 'Exchange taker fees.',
    'docs.sec3_li2': 'Simulated network withdrawal rebalancing fees.',
    'docs.sec3_li3': 'Latency price drift safety buffer.',
    'docs.sec3_li4': 'Real slippage from L2 depth book walking.',
    'docs.sec4_title': 'Architecture',
    'docs.sec4_p1': 'Structured as a clean, modular pnpm monorepo separating logic, configuration, and interfaces.',
    'docs.sec4_workspace_title': 'Workspace Topology',
    'docs.sec4_li1_desc': 'packages/core — domain calculations and depth-walking.',
    'docs.sec4_li2_desc': 'packages/config — fee models, exchange parameters, and schemas.',
    'docs.sec4_li3_desc': 'packages/testing — synthetic data generation and test suites.',
    'docs.sec4_li4_desc': 'apps/bot — backend engine, WS feeds, and simulation loop.',
    'docs.sec4_li5_desc': 'apps/web — responsive Next.js terminal dashboard.',
    'docs.sec5_title': 'Persistence Layer',
    'docs.sec5_p1': 'Supports fast, zero-config local JSON persistence (`db.json`) with auto-upgrade to PostgreSQL via Supabase when credentials are detected.',
    'docs.sec5_modes_title': 'Storage Modes',
    'docs.sec5_p2_1': 'Local Mode: Fast in-memory state with JSON backup.',
    'docs.sec5_p3': 'Supabase Mode: Persistent cloud storage with PostgreSQL.',
    
    'markets.cex_grid_title': '5-Exchange Spot Tickers',
    'markets.cex_grid_desc': 'Real-time L1 pricing, midpoints, and depth across all five connected exchanges.',
    'markets.spread_matrix_title': 'Cross-Venue 5x5 Net Spread Matrix',
    'markets.spread_matrix_desc': 'Real-time net spread expectations after CEX taker fees, slippage safety buffers, and stablecoin basis costs.',
    'markets.exchange_short': 'Venue',
    'markets.bid_short': 'Bid',
    'markets.ask_short': 'Ask',
    'markets.spread_short': 'Spread',
    'markets.mid_short': 'Mid',
    'markets.depth_short': 'Depth',
    'markets.profitable': 'Profitable',
    'markets.source_venue': 'Source Venue',
    'markets.target_venue': 'Target Venue',
    'markets.swap_title': 'Swap route direction',
    'markets.status_live': 'Live',
    'markets.status_connecting': 'Conn...',
    'markets.ask_to_bid': 'Ask → Bid',
    'markets.cross_basis': 'Cross Basis',
    'markets.mid_points_title': 'Exchange Mid Points',
    'markets.spread_differential': 'Spread differential:',
    'home.terminal_badge': 'Institutional Terminal',

    // AI Quant Copilot Workspace (English)
    'nav.copilot': 'AI Copilot',
    'copilot.title': 'AI Quant Command Center',
    'copilot.subtitle': 'Supervised AI Mode (Advisory-Only)',
    'copilot.model': 'Model Selector',
    'copilot.presets': 'Scenario Preset Queries',
    'copilot.composer': 'Command Composer',
    'copilot.placeholder': 'Type a quantitative command or select a preset chip...',
    'copilot.streaming': 'AI is evaluating micro-market order books...',
    'copilot.stream_done': 'Analysis completed',
    'copilot.rationale': 'Quantitative Rationale',
    'copilot.confidence': 'Confidence Score',
    'copilot.tools': 'Active Tool Execution Log',
    'copilot.apply': 'Apply Suggested Parameters',
    'copilot.load': 'Load Suggestion',
    'copilot.audit': 'Copilot Audit Trail (Append-Only Database Log)',
    'copilot.audit_col_time': 'Logged At',
    'copilot.audit_col_scenario': 'Scenario',
    'copilot.audit_col_action': 'Operator Action',
    'copilot.audit_col_decision': 'System Decision',
    'copilot.audit_col_latency': 'Latency',
    'copilot.audit_col_source': 'Source Panel',
    'copilot.audit_empty': 'No audit logs recorded in this session.',
    'widget.ai_advisor': 'AI Quant Advisor',
    'widget.ai_advisor_sub': 'Supervised Parameter Guidance',
    'widget.ai_diagnostics': 'AI Telemetry Diagnostics',
    'widget.ai_diagnostics_sub': 'Real-time Connection Audit',
    'widget.ai_critique': 'AI Execution Critique',
    'widget.ai_critique_sub': 'VWAP & Slippage Post-Mortem',
    'widget.ai_explain': 'AI Spread Explainability',
    'widget.ai_explain_sub': 'Cost & Fee Drag Attribution',
    'widget.ai_apply_btn': 'Apply Suggested Parameters',
    'widget.ai_review_btn': 'Review AI Proposal',
    'widget.ai_advisory_only': 'Live AI (GPT-4o-mini) Active',
    'copilot.desc': 'Quantitative analysis, latency tracking, L2 depth audits, and risk modeling.',
    'copilot.presets_desc': 'Click a quantitative directive below to execute deterministic simulation walks',
    'copilot.execute': '⚡ EXECUTE',
    'copilot.thinking': 'AI RUN TIME: SEARCHING telemetries...',
    'copilot.invoking': 'invoking...',
    'copilot.rationale_desc': 'Mathematical decision audit',
    'copilot.zscore_rationale': 'Z-Score Rationale',
    'copilot.algorithmic_walk': 'Algorithmic Deep Walk',
    'copilot.awaiting_execution': 'Awaiting query execution... Explainability models will map dynamically.',
    'copilot.governance': '🛡️ Operational Governance',
    'copilot.audit_desc': 'Real-time audit log of all testnet runs tracked by active session ID',
    'copilot.secure_ledger': 'Secure Ledger:',
    'copilot.append_only': 'APPEND-ONLY (DB TRIGGER ENFORCED)',
    'copilot.reconciling': 'Reconciling immutable database ledger records...',
    'copilot.drawer_title': '🔍 AI Review Proposal Drawer',
    'copilot.drawer_subtitle': 'Operator validation gateway',
    'copilot.telemetry_overview': 'Telemetry Overview',
    'copilot.model_label': 'Model:',
    'copilot.source_label': 'Source:',
    'copilot.confidence_label': 'Confidence:',
    'copilot.latency_label': 'Latency:',
    'copilot.execution_rationale': 'Execution Rationale',
    'copilot.safety_evaluation': 'Safety Evaluation',
    'copilot.dismiss': 'DISMISS',
    'nav.copilot_settings': 'Quant Copilot Engine Settings',
  },
  es: {
    // Navigation Sidebar
    'nav.overview': 'Resumen',
    'nav.markets': 'Mercados',
    'nav.opportunities': 'Oportunidades',
    'nav.trades': 'Historial',
    'nav.wallets': 'Reservas',
    'nav.risk': 'Control de Riesgo',
    'nav.health': 'Telemetría',
    'nav.docs': 'Documentación',
    'nav.changelog': 'Notas de Build',
    'nav.status': 'ESTADO DEL NODO:',
    'nav.live': 'EN VIVO',
    'nav.toggle_menu': 'Abrir menú',
    'footer.terms': 'Términos de Servicio',
    'footer.privacy': 'Política de Privacidad',
    'footer.sim_only': 'Entorno Testnet Activo',
    'footer.secure_node': 'NODO SEGURO',
    
    // Header Ticker
    'ticker.btc_spot': 'SPOT DE BTC:',
    'ticker.detection': 'DETECCIÓN:',
    'ticker.p99': 'CÓMPUTO P99:',
    'ticker.feeds': 'CANALES:',
    'ticker.feeds_suffix': 'activos',
    'ticker.sim_equity': 'PATRIMONIO:',
    'ticker.streaming': '● TRANSMITIENDO',
    'ticker.connecting': '○ CONECTANDO',
    
    // Overview Dashboard
    'overview.title': 'Consola de Valoración Cuantitativa',
    'overview.subtitle': 'Motor de valoración L2 y motor de ejecución multi-exchange en tiempo real.',
    'overview.total_profit': 'P&L Neto',
    'overview.win_rate': 'Tasa de Acierto',
    'overview.sharpe': 'Sharpe',
    'overview.mean_latency': 'Cómputo Medio',
    'overview.p99_latency': 'Cómputo p99',
    'overview.books_sec': 'Rendimiento (Libros/seg)',
    'overview.books_processed': 'Total Libros Evaluados',
    'overview.opps_detected': 'Oportunidades Detectadas',
    'overview.pnl_growth': 'Curva de Patrimonio Acumulado (Base 100k USD)',
    'overview.recent_trades': 'Ejecuciones Recientes',
    'overview.recent_opps': 'Flujo de Spreads de Arbitraje',
    'overview.no_trades': 'Esperando spreads rentables. La ejecución se dispara automáticamente.',
    'overview.no_opps': 'Reconciliando flujos de WebSocket en vivo de exchanges conectados...',
    'overview.pnl_chart': 'P&L ACUMULADO',
    'overview.under_cooldown': 'Disyuntor Activo - Modo de Enfriamiento',
    'overview.monitor_btn': 'Libros de Órdenes',
    'overview.risk_btn': 'Controles de Riesgo',
    'overview.portfolio_equity': 'PATRIMONIO DE CARTERA',
    'overview.initial_reserve': 'Asignación Inicial de 100k USD',
    'overview.sim_net_pnl': 'PNL NETO EN VIVO',
    'overview.after_slippage_fees': 'Neto de Deslizamiento y Comisiones',
    'overview.win_rate_label': 'TASA DE ACIERTO',
    'overview.win_rate_sub': 'Controles de deslizamiento armados',
    'overview.total_trades': 'TOTAL DE OPERACIONES',
    'overview.avg_trade_prefix': 'Prom:',
    'overview.avg_trade_suffix': '/ operación',
    'overview.sharpe_ratio': 'RATIO DE SHARPE',
    'overview.sharpe_sub': 'Tasa libre de riesgo: 0.0%',
    'overview.sharpe_building': 'Calculando',
    'overview.compute': 'cómputo',
    'overview.detection_latency': 'LATENCIA DE DETECCIÓN',
    'overview.books': 'libros',
    'overview.windows': 'ventanas',
    'overview.pnl_chart_title': 'PnL Acumulado',
    'overview.pnl_chart_sub': 'Curva de patrimonio en vivo ejecución por ejecución',
    'overview.real_time': 'TIEMPO REAL',
    'overview.sim_context': 'Contexto de Ejecución',
    'overview.core_algorithm': 'BUCLE DE VALORACIÓN CENTRAL:',
    'overview.core_algorithm_desc': 'Escanea todos los pares dirigidos en 5 exchanges en vivo (Binance, Kraken, Coinbase, OKX, Bybit). Dimensiona posiciones mediante recorrido L2 y verifica spreads netos tras comisiones taker, deslizamiento, base stablecoin y derivas de latencia.',
    'overview.sim_rules': 'REGLAS DE EJECUCIÓN:',
    'overview.sim_rules_desc': 'Las operaciones se ejecutan en Testnet. Los balances de wallets se restablecen automáticamente al alcanzar límites o caer de los umbrales base.',
    'overview.last_update': 'Última Actualización:',
    'overview.awaiting_data': 'Esperando telemetría...',
    'overview.recent_executions': 'Ejecuciones Recientes',
    'overview.trade_ledger_sub': 'Registros de auditoría',
    'overview.view_all_btn': 'Abrir Registros →',
    'overview.awaiting_trades': 'Esperando spreads rentables. Calibra los parámetros de riesgo para ampliar los márgenes de captura.',
    
    // Triangular Arbitrage panel
    'tri.title': 'Arbitraje Triangular',
    'tri.subtitle': 'Ciclo Binance Spot: USDT · BTC · ETH',
    'tri.unavailable': 'Esperando patas ETH de Binance...',
    'tri.gross_edge': 'Margen Bruto',
    'tri.fee_cost': 'Arrastre de Comisión (3 Patas)',
    'tri.net_edge': 'Margen Neto',
    'tri.notional': 'Nocional',
    'tri.exp_profit': 'Margen Esperado',
    'tri.executed': 'Ciclos Ejecutados',
    'tri.profitable': 'Rentable',
    'tri.below_floor': 'Bajo el Piso de Comisión',

    // Home Hero & Intro
    'home.hero_subtitle': 'Motor de arbitraje de Bitcoin entre exchanges en tiempo real',
    'home.metric_venues': '5 Exchanges Conectados',
    'home.metric_books': 'Profundidad L2 en Vivo',
    'home.metric_execution': 'Ejecución Testnet',
    'home.metric_strategy': 'Entre-Exchanges + Triangular',
    'home.cta_opportunities': 'Flujo de Arbitraje',
    'home.cta_trades': 'Libro de Operaciones',
    'home.inst_bullet1_title': 'Canales de Datos',
    'home.inst_bullet1_desc': 'Snapshots públicos de baja latencia transmitidos mediante WebSockets.',
    'home.inst_bullet2_title': 'Cobertura Matemática',
    'home.inst_bullet2_desc': 'Rendimiento neto ajustado por profundidad L2, comisiones, deslizamiento y deriva de precios.',
    'home.inst_bullet3_title': 'Seguimiento de Reservas',
    'home.inst_bullet3_desc': 'Reconciliación de balances en tiempo real, enrutamiento y persistencia en base de datos.',

    // Table Headers
    'table.timestamp': 'HORARIO',
    'table.route': 'RUTA',
    'table.volume': 'VOLUMEN',
    'table.buy_price': 'PRECIO COMPRA',
    'table.sell_price': 'PRECIO VENTA',
    'table.gross_pnl': 'P&L BRUTO',
    'table.net_pnl': 'P&L NETO',

    // Comparative Markets
    'markets.title': 'Mercados L2 Comparativos',
    'markets.subtitle': 'Sincronización L2 en tiempo real y visualización de liquidez cruzada.',
    'markets.exchange_label': 'Plataforma Exchange',
    'markets.symbol_label': 'Par de Trading',
    'markets.top_bids': 'Mejores Ofertas (Compradores)',
    'markets.top_asks': 'Mejores Demandas (Vendedores)',
    'markets.price': 'Precio (USD)',
    'markets.size': 'Tamaño (BTC)',
    'markets.total': 'Total',
    'markets.no_depth': 'Conectando canal WebSocket...',
    'markets.depth_visualizer': 'Visualización Gráfica de Profundidad L2 (BTC/USDT)',
    'markets.route_permutation': 'PERMUTACIÓN DE RUTA',
    'markets.arb_window': 'VENTANA DE ARBITRAJE',
    'markets.no_spread': 'SIN SPREAD',
    'markets.gross_spread': 'SPREAD BRUTO',
    'markets.est_fees': 'COMISIONES Y DESLIZAMIENTO',
    'markets.net_estimate': 'ESTIMACIÓN NETO',
    'markets.unprofitable': 'NO RENTABLE',
    'markets.liquidity_title': 'Análisis de Profundidad de Liquidez',
    'markets.liquidity_sub': 'Volumen acumulado en torno al precio medio',
    'markets.awaiting_books': 'Sincronizando libros de órdenes por WebSocket...',
    'markets.binance_l2': 'Binance Spot L2 (BTC/USDT)',
    'markets.kraken_l2': 'Kraken Spot L2 (XBT/USD)',
    'markets.binance_l2_desc': 'Comisión Taker: 0.04% | Datos cada 100ms',
    'markets.kraken_l2_desc': 'Comisión Taker: 0.10% | Suma CRC32 Activa',
    'markets.mid_price': 'PRECIO MEDIO',
    'markets.bids_buy': 'Ofertas (Compra)',
    'markets.asks_sell': 'Demandas (Venta)',
    'markets.awaiting_ws': 'Esperando WebSocket...',
    'markets.reference_aggregators': 'Agregadores de Referencia',
    'markets.reference_desc': 'Verifica spreads en vivo y volumen de liquidez frente a plataformas globales.',

    // Live Opportunities
    'opps.title': 'Registro de Spreads de Arbitraje',
    'opps.subtitle': 'Flujo en tiempo real de spreads candidatos filtrados por parámetros de riesgo.',
    'opps.filter_all': 'Todos los Spreads',
    'opps.filter_executed': 'Ejecutados',
    'opps.filter_skipped': 'Omitidos',
    'opps.col_time': 'Detectada el',
    'opps.col_pair': 'Transición de Venue',
    'opps.col_gross': 'Spread Bruto',
    'opps.col_net': 'Spread Neto',
    'opps.col_volume': 'Volumen Máx',
    'opps.col_profit': 'Beneficio Esp.',
    'opps.col_confidence': 'Conf. (σ)',
    'opps.col_status': 'Estado',
    'opps.col_reason': 'Acción / Razón',
    'opps.executed': 'EJECUTADO',
    'opps.skipped': 'OMITIDO',
    'opps.no_opps': 'No se han evaluado spreads aún. Ingeriendo WS en vivo...',
    'opps.title_header': 'Oportunidades en Vivo',
    'opps.subtitle_header': 'Flujo en tiempo real de spreads candidatos filtrados por parámetros de riesgo.',
    'opps.filter_all_label': 'Todos los Feeds',
    'opps.filter_executed_label': 'Ejecutadas',
    'opps.filter_skipped_label': 'Omitidas',
    'opps.col_ask_buy': 'ASK (COMPRA)',
    'opps.col_bid_sell': 'BID (VENTA)',
    'opps.no_opps_filter': 'No se encontraron spreads para el filtro activo.',
    'opps.success_reason': 'Dimensionado y Ejecutado con Éxito',
    'opps.table_sub': 'Calculado desde snapshots de libros de órdenes',
    'opps.zscore_tooltip': 'Confianza estadística: z-score del spread frente al historial. Valores altos indican reversión estadística.',

    // Executed Trades
    'trades.title': 'Registro de Operaciones Ejecutadas',
    'trades.subtitle': 'Ejecuciones Testnet respetando la liquidez L2 recorrida, el deslizamiento spot y las tasas taker.',
    'trades.export': 'Exportar Historial (CSV)',
    'trades.col_time': 'Ejecutado el',
    'trades.col_id': 'ID de Transacción',
    'trades.col_venues': 'Dirección',
    'trades.col_buy_price': 'Precio Compra (VWAP)',
    'trades.col_sell_price': 'Precio Venta (VWAP)',
    'trades.col_volume': 'Volumen (BTC)',
    'trades.col_gross': 'P&L Bruto',
    'trades.col_fees': 'Comisiones Taker',
    'trades.col_slippage': 'Deslizamiento',
    'trades.col_net': 'Beneficio Neto',
    'trades.no_trades': 'Sin transacciones en Testnet ejecutadas. Las curvas se actualizan al completarse.',
    'trades.title_header': 'Registro de Operaciones Testnet',
    'trades.subtitle_header': 'Registros de auditoría de todas las ejecuciones de arbitraje completadas y cubiertas.',
    'trades.export_btn': 'Exportar CSV',
    'trades.accumulated_pnl': 'P&L NETO ACUMULADO',
    'trades.win_rate_count': 'TASA DE ACIERTO / TOTAL',
    'trades.total_fees': 'COMISIONES TAKER TOTALES',
    'trades.slippage_loss': 'PÉRDIDA POR DESLIZAMIENTO',
    'trades.table_title': 'Libro de Operaciones',
    'trades.table_sub': 'Logs de ejecución',
    'trades.no_trades_message': 'Sin ejecuciones. Esperando spreads que cubran la totalidad de los costes operativos.',

    // Live Wallets
    'wallets.title': 'Asignación de Capital',
    'wallets.subtitle': 'Saldos en vivo en tiempo real. Los fondos se rebalancean automáticamente al capturar spreads.',
    'wallets.exchange': 'Exchange Venue',
    'wallets.asset': 'Activo',
    'wallets.free': 'Saldo Disponible',
    'wallets.locked': 'Saldo Bloqueado',
    'wallets.total': 'Saldo Total',
    'wallets.value_usd': 'Valor Aprox (USD)',
    'wallets.reset_btn': 'Restablecer Saldos',
    'wallets.reset_warning': 'Esto restaura todas las carteras de los exchanges a los valores de base.',
    'wallets.title_header': 'Reservas de Capital en Testnet',
    'wallets.subtitle_header': 'Reservas de liquidez en tiempo real, desglose de activos y perfiles de exposición.',
    'wallets.pool_title': 'Fondo de Saldos',
    'wallets.active_reserve': 'RESERVA ACTIVA',
    'wallets.free_label': 'Disponible',
    'wallets.locked_label': 'Bloqueado',
    'wallets.oversight_title': 'Supervisión de Asignación de Activos',
    'wallets.agg_btc': 'EXPOSICIÓN TOTAL SPOT DE BTC:',
    'wallets.agg_quote': 'EXPOSICIÓN TOTAL DE EFECTIVO COTIZADO:',

    // Risk & Settings
    'risk.title': 'Consola de Supervisión de Riesgos',
    'risk.subtitle': 'Calibración de spreads, configuración de disyuntores y límites de exposición.',
    'risk.circuit_breakers': 'Disyuntores del Sistema',
    'risk.cooldown_status': 'Estado del disyuntor',
    'risk.cooldown_active': 'ENFRIAMIENTO ACTIVO (MOTOR PAUSADO)',
    'risk.cooldown_inactive': 'NOMINAL (EJECUCIÓN)',
    'risk.exchanges_exposure': 'Controles de Exposición',
    'risk.global_btc': 'Límite Global de Exposición BTC',
    'risk.global_quote': 'Límite Global de Exposición Quote',
    'risk.losses_limit': 'Disyuntor por Pérdidas Consecutivas',
    'risk.volatility_breaker': 'Salvaguarda de Colapso por Volatilidad',
    'risk.volatility_limit': 'Divergencia Máxima de Precios',
    'risk.settings_form': 'Panel de Calibración',
    'risk.min_net_profit': 'Beneficio Neto Mín (USD)',
    'risk.max_btc_per_cex': 'Asignación Máx BTC por CEX',
    'risk.max_quote_per_cex': 'Asignación Máx Quote por CEX',
    'risk.latency_bps': 'Desviación de Latencia (BPS)',
    'risk.slippage_bps': 'Colchón de Deslizamiento (BPS)',
    'risk.trades_per_min': 'Velocidad Máx de Operación (por min)',
    'risk.save_btn': 'Guardar Configuración',
    'risk.pass_placeholder': 'Introduce clave de API...',
    'risk.success_save': 'Configuración guardada y persistida correctamente.',
    'risk.error_save': 'Error al actualizar. Comprueba clave de API.',
    'risk.cooldown_reason': 'Causa de Disparo: Incurrió en 3 pérdidas consecutivas debido a deslizamientos de mercado sintéticos.',
    'risk.title_header': 'Consola de Supervisión de Riesgos',
    'risk.subtitle_header': 'Calibración de spreads, configuración de disyuntores y límites de exposición.',
    'risk.system_breaker': 'DISYUNTOR DE SEGURIDAD',
    'risk.engine_health': 'SALUD DEL MOTOR DE RIESGO',
    'risk.circuit_status': 'ESTADO DEL CIRCUITO',
    'risk.default_reason': 'Todos los parámetros operando dentro de límites nominales.',
    'risk.consecutive_losses': 'PÉRDIDAS CONSECUTIVAS',
    'risk.cooldown_timer': 'TEMPORIZADOR DE ENFRIAMIENTO',
    'risk.seconds_remaining': 's restantes',
    'risk.inactive': 'INACTIVO',
    'risk.emergency_ops': 'Operaciones de Emergencia',
    'risk.rebalance_title': 'Restablecer Saldos',
    'risk.rebalance_desc': 'Borra logs, oportunidades y libros contables, restableciendo las carteras a los valores iniciales.',
    'risk.resetting_btn': 'Restableciendo...',
    'risk.reset_balances_btn': 'RESTABLECER BALANCES',
    'risk.settings_title': 'Parámetros de Riesgo',
    'risk.settings_desc': 'Calibra los parámetros de recorrido L2 y coberturas de tarifas/latencia.',
    'risk.min_profit_title': 'Beneficio Neto Mínimo',
    'risk.min_profit_desc': 'Umbral de spread necesario para activar órdenes en Testnet',
    'risk.max_alloc_title': 'Techo de Asignación Máxima',
    'risk.max_alloc_desc': 'Límite de exposición máxima para el tamaño de transacciones individuales',
    'risk.latency_title': 'Desviación de Latencia',
    'risk.latency_desc': '1 BPS = 0.01%. Margen de beneficio esperado para rechazos por retraso de WebSocket',
    'risk.slippage_title': 'Colchón de Deslizamiento',
    'risk.slippage_desc': 'Colchón de seguridad adicional deducido de los precios de ejecución en Testnet',
    'risk.exec_latency_title': 'Latencia de Ejecución',
    'risk.exec_latency_desc': 'Latencia modelada de orden a fill. La deriva de precio en esta ventana aborta órdenes si el margen se desvanece.',
    'risk.pause_aria': 'Alternar pausa de emergencia',
    'risk.saving_msg': 'Guardando...',
    'risk.success_msg': '✅ Configuración persistida con éxito.',
    'risk.error_msg': '❌ Error al guardar la configuración.',
    'risk.save_config_btn': 'Guardar Ajustes',
    'risk.persisting_btn': 'Persistiendo...',
    'risk.dialog_title': 'Restablecer Estado Testnet',
    'risk.dialog_desc': 'ADVERTENCIA: Esta acción eliminará todo el historial de transacciones, oportunidades y logs, devolviendo los wallets a las asignaciones iniciales.',
    'risk.dialog_body': 'Esta acción borra los datos del libro diario y restaura los balances base de forma irreversible.',
    'risk.cancel': 'Cancelar',
    'risk.confirm_reset': 'Confirmar Restablecimiento',
    'risk.alert_success': '🔄 Estado de Testnet restablecido con éxito.',
    'risk.alert_error': '❌ Error al restablecer Testnet.',

    // System Health
    'health.title': 'Salud y Canales del Sistema',
    'health.subtitle': 'Estado de conexiones WebSocket, latencias, ping-pongs y reconexión en vivo.',
    'health.connection_channels': 'Canales de Conexión WebSocket',
    'health.venue': 'Exchange Venue',
    'health.stream_url': 'Endpoint WebSocket',
    'health.status_col': 'Estado del Canal',
    'health.reconnects': 'Reconexiones',
    'health.last_msg': 'Último Latido Recibido',
    'health.system_metrics': 'Métricas Centrales del Motor',
    'health.uptime': 'Tiempo de Actividad del Backend',
    'health.api_endpoints': 'Estado y Prueba de la API REST',
    'health.title_header': 'Telemetría de Salud del Sistema',
    'health.subtitle_header': 'Monitoreo WebSocket en tiempo real, latidos y logs de auditoría.',
    'health.feed_suffix': 'Canal',
    'health.connected': 'CONECTADO',
    'health.disconnected': 'DESCONECTADO',
    'health.reconnect_counter': 'CONTADOR DE RECONEXIONES:',
    'health.last_heartbeat': 'ÚLTIMO LATIDO:',
    'health.no_messages': 'Sin mensajes',
    'health.terminal_uptime': 'UPTIME DE LA TERMINAL',
    'health.client_socket': 'CONEXIÓN DE SOCKET CLIENTE',
    'health.socket_stable': 'ESTABLE',
    'health.socket_connecting': 'CONECTANDO...',
    'health.logged_events': 'EVENTOS REGISTRADOS',
    'health.records_label': 'registros',
    'health.detection_latency': 'LATENCIA DE DETECCIÓN',
    'health.wire_label': 'red',
    'health.compute_label': 'cómputo',
    'health.engine_status': 'ESTADO DEL MOTOR',
    'health.engine_live': 'ACTIVO · OPERANDO',
    'health.engine_paused': 'PAUSADO',
    'health.engine_idle': 'INACTIVO · SIN EVALS RECIENTES',
    'health.last_activity': 'ÚLTIMA EVALUACIÓN',
    'health.self_heals': 'AUTO-REPARACIONES',
    'health.fill_aborts': 'ABORTOS DE FILL',
    'health.fill_window': 'ventana de fill',
    'health.audit_trails': 'Registros de Auditoría de la Plataforma',
    'health.timestamp_col': 'HORARIO',
    'health.type_col': 'TIPO',
    'health.desc_col': 'MENSAJE DESCRIPTIVO DEL EVENTO',
    'health.no_events': 'Aún no se han registrado eventos en el sistema.',

    // Platform Docs
    'docs.title_header': 'Documentación de la Plataforma',
    'docs.subtitle_header': 'Referencia técnica, mecánica de ejecución y topología de la arquitectura.',
    'docs.flow_market_data': 'Datos de Mercado',
    'docs.flow_opportunity': 'Motor de Oportunidades',
    'docs.flow_execution': 'Motor de Ejecución Testnet',
    'docs.flow_pnl': 'Seguimiento de PnL',
    'docs.sec1_title': 'Arbitraje entre Exchanges',
    'docs.sec1_p1': 'Aurex es un simulador de arbitraje entre exchanges en tiempo real de grado institucional. Agrega profundidad L2 en cinco exchanges conectados para calcular, ordenar y ejecutar de spreads netos descontando comisiones, deslizamiento y latencias.',
    'docs.sec2_title': 'Lógica de Ejecución',
    'docs.sec2_p1': 'El motor recorre libros L2 para calcular los precios ejecutables reales, mapeando las restricciones de volumen reales para evitar ganancias en papel fantasmas.',
    'docs.sec2_seq_title': 'Secuencia de evaluación',
    'docs.sec2_card_step1': 'Inicializar con un volumen base conservador.',
    'docs.sec2_card_step2': 'Recorrer ofertas de venta en exchange barato y ofertas de compra en exchange caro.',
    'docs.sec2_card_step3': 'Calcular precios promedio ponderados (VWAP) desde la profundidad.',
    'docs.sec2_card_step4': 'Deducir comisiones taker, colchón de latencia y deslizamiento.',
    'docs.sec2_card_step5': 'Maximizar rentabilidad mediante expansión iterativa de volumen.',
    'docs.sec3_title': 'Marco de Costes',
    'docs.sec3_p1': 'Los spreads se evalúan netos de comisiones de exchange, deslizamiento, derivas de latencia y comisiones de paridad stablecoin USD/USDT.',
    'docs.sec3_costs_title': 'Costes Deducidos',
    'docs.sec3_li1': 'Comisiones Taker de exchanges.',
    'docs.sec3_li2': 'Comisiones estimadas de rebalanceo y retiro por blockchain.',
    'docs.sec3_li3': 'Amortiguador de seguridad por derivas de latencia.',
    'docs.sec3_li4': 'Deslizamiento real por recorrido de profundidad L2.',
    'docs.sec4_title': 'Arquitectura',
    'docs.sec4_p1': 'Estructurado como un monorepositorio pnpm limpio y modular, separando lógica, configuración y dashboards.',
    'docs.sec4_workspace_title': 'Topología del Espacio de Trabajo',
    'docs.sec4_li1_desc': 'packages/core — cálculos de dominio y recorrido L2.',
    'docs.sec4_li2_desc': 'packages/config — modelos de comisiones y parámetros de exchanges.',
    'docs.sec4_li3_desc': 'packages/testing — suite de pruebas y generación de fixtures.',
    'docs.sec4_li4_desc': 'apps/bot — motor backend, feeds WS y bucles de ejecución.',
    'docs.sec4_li5_desc': 'apps/web — consola responsiva Next.js.',
    'docs.sec5_title': 'Capa de Persistencia',
    'docs.sec5_p1': 'Soporta persistencia local JSON rápida (`db.json`) con escalado transparente a PostgreSQL a través de Supabase al detectar credenciales en producción.',
    'docs.sec5_modes_title': 'Modos de Almacenamiento',
    'docs.sec5_p2_1': 'Modo Local: Estado en memoria rápido con copias JSON de respaldo.',
    'docs.sec5_p3': 'Modo Supabase: Persistencia en la nube con PostgreSQL de Supabase.',
    
    'markets.cex_grid_title': 'Precios Spot de los 5 Exchanges',
    'markets.cex_grid_desc': 'Precios L1 en tiempo real, puntos medios y profundidad en las cinco plataformas conectadas.',
    'markets.spread_matrix_title': 'Matriz de Spreads Netos 5x5 entre Exchanges',
    'markets.spread_matrix_desc': 'Spreads netos esperados en tiempo real descontando comisiones taker VIP, colchón de deslizamiento y comisiones de paridad de establecoin.',
    'markets.exchange_short': 'Exchange',
    'markets.bid_short': 'Bid',
    'markets.ask_short': 'Ask',
    'markets.spread_short': 'Spread',
    'markets.mid_short': 'Medio',
    'markets.depth_short': 'Profundidad',
    'markets.profitable': 'Rentable',
    'markets.source_venue': 'Exchange Origen',
    'markets.target_venue': 'Exchange Destino',
    'markets.swap_title': 'Invertir dirección de la ruta',
    'markets.status_live': 'En Vivo',
    'markets.status_connecting': 'Conn...',
    'markets.ask_to_bid': 'Ask → Bid',
    'markets.cross_basis': 'Basis Cruzado',
    'markets.mid_points_title': 'Puntos Medios por Exchange',
    'markets.source_l2': 'Libro L2 del exchange origen',
    'markets.target_l2': 'Libro L2 del exchange destino',
    'home.terminal_badge': 'Terminal Institucional',

    // AI Quant Copilot Workspace (Spanish)
    'nav.copilot': 'Copiloto IA',
    'copilot.title': 'Centro de Comando Cuantitativo IA',
    'copilot.subtitle': 'Modo de IA Supervisada (Solo Asesoría)',
    'copilot.model': 'Selector de Modelo',
    'copilot.presets': 'Escenarios Predefinidos',
    'copilot.composer': 'Redactor de Comando',
    'copilot.placeholder': 'Escriba un comando cuantitativo o seleccione un escenario...',
    'copilot.streaming': 'La IA está evaluando los libros de órdenes del micro-mercado...',
    'copilot.stream_done': 'Análisis completado',
    'copilot.rationale': 'Razonamiento Cuantitativo',
    'copilot.confidence': 'Índice de Confianza',
    'copilot.tools': 'Registro de Ejecución de Herramientas Activas',
    'copilot.apply': 'Aplicar Parámetros Sugeridos',
    'copilot.load': 'Cargar Sugerencia',
    'copilot.audit': 'Historial de Auditoría de Copiloto (Registro Inmutable en BD)',
    'copilot.audit_col_time': 'Registrado el',
    'copilot.audit_col_scenario': 'Escenario',
    'copilot.audit_col_action': 'Acción del Operador',
    'copilot.audit_col_decision': 'Decisión del Sistema',
    'copilot.audit_col_latency': 'Latencia',
    'copilot.audit_col_source': 'Panel de Origen',
    'copilot.audit_empty': 'No se han registrado auditorías en esta sesión.',
    'widget.ai_advisor': 'Asesor Cuantitativo IA',
    'widget.ai_advisor_sub': 'Guía de Parámetros Supervisada',
    'widget.ai_diagnostics': 'Diagnósticos de Telemetría IA',
    'widget.ai_diagnostics_sub': 'Auditoría de Conexión en Tiempo Real',
    'widget.ai_critique': 'Crítica de Ejecución IA',
    'widget.ai_critique_sub': 'Análisis de VWAP y Deslizamiento',
    'widget.ai_explain': 'Explicación del Diferencial IA',
    'widget.ai_explain_sub': 'Atribución de Costos y Comisiones',
    'widget.ai_apply_btn': 'Aplicar Parámetros Sugeridos',
    'widget.ai_review_btn': 'Revisar Propuesta IA',
    'widget.ai_advisory_only': 'Motor IA (GPT-4o-mini) Activo',
    'copilot.desc': 'Análisis cuantitativo, seguimiento de latencia, auditorías de profundidad L2 y modelado de riesgo.',
    'copilot.presets_desc': 'Haga clic en una directiva cuantitativa a continuación para ejecutar recorridos de ejecución deterministas',
    'copilot.execute': '⚡ EJECUTAR',
    'copilot.thinking': 'TIEMPO DE EJECUCIÓN IA: BUSCANDO telemetrías...',
    'copilot.invoking': 'invocando...',
    'copilot.rationale_desc': 'Auditoría de decisión matemática',
    'copilot.zscore_rationale': 'Razonamiento de Z-Score',
    'copilot.algorithmic_walk': 'Recorrido Algorítmico Profundo',
    'copilot.awaiting_execution': 'Esperando ejecución de consulta... Los modelos de explicabilidad se mapearán dinámicamente.',
    'copilot.governance': '🛡️ Gobernanza Operativa',
    'copilot.audit_desc': 'Registro de auditoría en tiempo real de todas las ejecuciones simuladas rastreadas por ID de sesión activa',
    'copilot.secure_ledger': 'Libro Seguro:',
    'copilot.append_only': 'SOLO AGREGAR (FORZADO POR TRIGGER BD)',
    'copilot.reconciling': 'Reconciliando registros inmutables del libro diario en la base de datos...',
    'copilot.drawer_title': '🔍 Panel de Revisión de Propuesta de IA',
    'copilot.drawer_subtitle': 'Puerta de enlace de validación del operador',
    'copilot.telemetry_overview': 'Resumen de Telemetría',
    'copilot.model_label': 'Modelo:',
    'copilot.source_label': 'Origen:',
    'copilot.confidence_label': 'Confianza:',
    'copilot.latency_label': 'Latencia:',
    'copilot.execution_rationale': 'Razonamiento de Ejecución',
    'copilot.safety_evaluation': 'Evaluación de Seguridad',
    'copilot.dismiss': 'DESCARTAR',
    'nav.copilot_settings': 'Ajustes del Motor de Copiloto IA',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('en');

  // Load language preference from localStorage on mount
  useEffect(() => {
    const saved = localStorage.getItem('aurex_lang');
    if (saved === 'en' || saved === 'es') {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('aurex_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
