'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Complete translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation Sidebar
    'nav.overview': 'Dashboard Overview',
    'nav.markets': 'Comparative Markets',
    'nav.opportunities': 'Live Opportunities',
    'nav.trades': 'Executed Trades',
    'nav.wallets': 'Simulated Wallets',
    'nav.risk': 'Risk & Settings',
    'nav.health': 'System Health',
    'nav.docs': 'Platform Docs',
    'nav.status': 'NODE STATUS:',
    'nav.live': 'LIVE',
    
    // Header Ticker
    'ticker.btc_spot': 'BTC SPOT:',
    'ticker.detection': 'DETECTION:',
    'ticker.feeds': 'FEEDS:',
    'ticker.feeds_suffix': 'live',
    'ticker.sim_equity': 'SIM EQUITY:',
    'ticker.streaming': '● STREAMING',
    'ticker.connecting': '○ CONNECTING',
    
    // Overview Dashboard
    'overview.title': 'Arbitrage Console Overview',
    'overview.subtitle': 'Real-time multi-CEX mathematical spread engine and execution simulator.',
    'overview.total_profit': 'Simulated Net Profit',
    'overview.win_rate': 'Simulation Win Rate',
    'overview.sharpe': 'Sharpe Ratio',
    'overview.mean_latency': 'Mean Latency',
    'overview.p99_latency': 'p99 Latency',
    'overview.books_sec': 'Throughput (Books/sec)',
    'overview.books_processed': 'Total Books Evaluated',
    'overview.opps_detected': 'Opps Detected',
    'overview.pnl_growth': 'Simulated Equity Growth (100k USD Base)',
    'overview.recent_trades': 'Recent Captured Spreads',
    'overview.recent_opps': 'Real-Time Spreads Feed',
    'overview.no_trades': 'No simulated trades executed yet. Spread windows will trigger automatic execution.',
    'overview.no_opps': 'Waiting for real-time WebSocket order book data from connected exchanges...',
    'overview.pnl_chart': 'PNL GROWTH',
    'overview.under_cooldown': 'Risk Breaker Active - Engine Cooling Down',
    'overview.monitor_btn': 'Monitor Order Books',
    'overview.risk_btn': 'Adjust Risk Parameters',
    'overview.portfolio_equity': 'PORTFOLIO EQUITY',
    'overview.initial_reserve': '100k USD Initial Reserve',
    'overview.sim_net_pnl': 'SIMULATED NET P&L',
    'overview.after_slippage_fees': 'After Slippage & Fees',
    'overview.win_rate_label': 'WIN RATE',
    'overview.win_rate_sub': 'Slippage loss checks active',
    'overview.total_trades': 'TOTAL TRADES',
    'overview.avg_trade_prefix': 'Avg:',
    'overview.avg_trade_suffix': '/ trade',
    'overview.sharpe_ratio': 'SHARPE RATIO',
    'overview.sharpe_sub': 'Risk-free rate: 0.0%',
    'overview.detection_latency': 'DETECTION LATENCY',
    'overview.books': 'books',
    'overview.windows': 'windows',
    'overview.pnl_chart_title': 'Cumulative PnL',
    'overview.pnl_chart_sub': 'Calculated at each simulated execution block',
    'overview.real_time': 'REAL-TIME',
    'overview.sim_context': 'Simulator Context',
    'overview.core_algorithm': 'CORE ALGORITHM:',
    'overview.core_algorithm_desc': 'Ranking every directed venue pair across 5 live exchanges (Binance, Kraken, Coinbase, OKX, Bybit), sizing each via L2 depth-walk and verifying spreads net of VIP-tier taker fees, slippage safety, and transfer costs — then executing the most profitable window.',
    'overview.sim_rules': 'SIMULATION RULES:',
    'overview.sim_rules_desc': 'Trades are strictly non-custodial and simulation-only. Balances automatically reset when reserves drain or positions cap.',
    'overview.last_update': 'Last Update:',
    'overview.awaiting_data': 'Awaiting data...',
    'overview.recent_executions': 'Recent Executions',
    'overview.trade_ledger_sub': 'Real-time trade ledger logs',
    'overview.view_all_btn': 'View All Ledger Logs →',
    'overview.awaiting_trades': 'Awaiting candidate trade opportunities... (Adjust risk thresholds to trigger logs)',
    
    // Home Hero & Intro
    'home.hero_subtitle': 'Real-time Bitcoin cross-exchange arbitrage simulator',
    'home.metric_venues': '5 Live Venues',
    'home.metric_books': 'Live L2 Books',
    'home.metric_execution': 'Simulated Execution',
    'home.cta_opportunities': 'View Live Opportunities',
    'home.cta_trades': 'Open Executed Trades',
    'home.inst_bullet1_title': 'Market Data Feeds',
    'home.inst_bullet1_desc': 'Public market data streamed in real-time from active exchanges.',
    'home.inst_bullet2_title': 'Spread Math Hedges',
    'home.inst_bullet2_desc': 'Net-profit evaluation strictly net of vip-tier CEX fees, slippage safety buffers, and network latency.',
    'home.inst_bullet3_title': 'Reserve Tracking',
    'home.inst_bullet3_desc': 'Automated simulated execution engine tracking wallet accounts, cumulative margins, and P&L ledger logs.',

    // Table Headers
    'table.timestamp': 'TIMESTAMP',
    'table.route': 'ROUTE',
    'table.volume': 'VOLUME',
    'table.buy_price': 'BUY PRICE',
    'table.sell_price': 'SELL PRICE',
    'table.gross_pnl': 'GROSS P&L',
    'table.net_pnl': 'NET P&L',

    // Comparative Markets
    'markets.title': 'Comparative L2 Markets',
    'markets.subtitle': 'Side-by-side real-time L2 order book depth tracking for cross-venue spreads.',
    'markets.exchange_label': 'Exchange Platform',
    'markets.symbol_label': 'Trading Pair Symbol',
    'markets.top_bids': 'Top Bids (Buyers)',
    'markets.top_asks': 'Top Asks (Sellers)',
    'markets.price': 'Price (USD)',
    'markets.size': 'Size (BTC)',
    'markets.total': 'Total',
    'markets.no_depth': 'Connecting CEX WebSocket feed...',
    'markets.depth_visualizer': 'L2 Order Book Depth Visualization (BTCUSDT)',
    'markets.route_permutation': 'ROUTE permutation',
    'markets.arb_window': 'ARBITRAGE WINDOW',
    'markets.no_spread': 'NO SPREAD',
    'markets.gross_spread': 'GROSS SPREAD',
    'markets.est_fees': 'EST FEES & COST',
    'markets.net_estimate': 'NET ESTIMATE',
    'markets.unprofitable': 'UNPROFITABLE',
    'markets.liquidity_title': 'Liquidity Depth Analysis',
    'markets.liquidity_sub': 'Cumulative bids vs asks quantity meeting at mid-price',
    'markets.awaiting_books': 'Awaiting live WebSocket order book updates...',
    'markets.binance_l2': 'Binance Spot L2 (BTC/USDT)',
    'markets.kraken_l2': 'Kraken Spot L2 (XBT/USD)',
    'markets.binance_l2_desc': 'VIP Taker Fee: 0.04% | Refreshed every 100ms',
    'markets.kraken_l2_desc': 'VIP Taker Fee: 0.10% | CRC32 Checksums Valid',
    'markets.mid_price': 'MID PRICE',
    'markets.bids_buy': 'Bids (Buy)',
    'markets.asks_sell': 'Asks (Sell)',
    'markets.awaiting_ws': 'Awaiting WebSocket...',
    'markets.reference_aggregators': 'Reference External Aggregators',
    'markets.reference_desc': 'Cross-check live spot spreads and liquidity volume structures against global reference charts.',

    // Live Opportunities
    'opps.title': 'Arbitrage Spreads Log',
    'opps.subtitle': 'Real-time ranking and logging of every cross-venue spread opportunity evaluated.',
    'opps.filter_all': 'All Opportunities',
    'opps.filter_executed': 'Executed Only',
    'opps.filter_skipped': 'Skipped Only',
    'opps.col_time': 'Detected At',
    'opps.col_pair': 'Venue Transition',
    'opps.col_gross': 'Gross Spread',
    'opps.col_net': 'Net Spread',
    'opps.col_volume': 'Max Volume',
    'opps.col_profit': 'Exp. Profit',
    'opps.col_confidence': 'Conf. (σ)',
    'opps.col_status': 'Status',
    'opps.col_reason': 'Action / Reason',
    'opps.executed': 'EXECUTED',
    'opps.skipped': 'SKIPPED',
    'opps.no_opps': 'No opportunities logged yet. Scanning websocket feeds...',
    'opps.title_header': 'Live Arbitrage Opportunities',
    'opps.subtitle_header': 'Real-time feed of candidate spreads evaluated by the core valuation loops.',
    'opps.filter_all_label': 'All Feeds',
    'opps.filter_executed_label': 'Executed',
    'opps.filter_skipped_label': 'Skipped',
    'opps.col_ask_buy': 'ASK (BUY)',
    'opps.col_bid_sell': 'BID (SELL)',
    'opps.no_opps_filter': 'No evaluated opportunities found matching active filter.',
    'opps.success_reason': 'Sized and Executed Successfully',
    'opps.table_sub': 'Calculated from order book snapshots',

    // Executed Trades
    'trades.title': 'Executed Trades Ledger',
    'trades.subtitle': 'Simulated executions respecting walked L2 liquidity, spot slippage, and taker fees.',
    'trades.export': 'Export Trades (CSV Sheet)',
    'trades.col_time': 'Executed At',
    'trades.col_id': 'Trade/Opportunity ID',
    'trades.col_venues': 'Direction',
    'trades.col_buy_price': 'Buy Price (walked)',
    'trades.col_sell_price': 'Sell Price (walked)',
    'trades.col_volume': 'Volume (BTC)',
    'trades.col_gross': 'Gross P&L',
    'trades.col_fees': 'Taker Fees Paid',
    'trades.col_slippage': 'Slippage Incurred',
    'trades.col_net': 'Net Profit',
    'trades.no_trades': 'No simulated trades executed yet. Profit curves update instantly upon fill.',
    'trades.title_header': 'Simulated Trade Ledger',
    'trades.subtitle_header': 'Audit logs of all risk-mitigated cross-venue arbitrage executions completed by the engine.',
    'trades.export_btn': 'Export Trades CSV',
    'trades.accumulated_pnl': 'SIM ACCUMULATED P&L',
    'trades.win_rate_count': 'WIN RATE / COUNT',
    'trades.total_fees': 'TOTAL TAKER FEES PAID',
    'trades.slippage_loss': 'SLIPPAGE SLIDE LOSS',
    'trades.table_title': 'Execution Ledger',
    'trades.table_sub': 'Real-time trade ledger logs',
    'trades.no_trades_message': 'No transactions executed yet. Awaiting a cross-venue window that clears all costs — adjust risk thresholds in Settings to widen the capture band.',

    // Simulated Wallets
    'wallets.title': 'Simulated Ledgers & Funding',
    'wallets.subtitle': 'Real-time multi-exchange simulated balances. Funds rebalance automatically on trade capture.',
    'wallets.exchange': 'Exchange Venue',
    'wallets.asset': 'Asset',
    'wallets.free': 'Free Amount',
    'wallets.locked': 'Locked Amount',
    'wallets.total': 'Total Balance',
    'wallets.value_usd': 'Approx Value (USD)',
    'wallets.reset_btn': 'Reset Simulator Accounts & Balances',
    'wallets.reset_warning': 'This will restore all simulated wallet allocations back to default funding.',
    'wallets.title_header': 'Simulated Capital Reserves',
    'wallets.subtitle_header': 'Monitor capital holdings, asset balances, and net quote-base exposures per active exchange.',
    'wallets.pool_title': 'Balance Pool',
    'wallets.active_reserve': 'ACTIVE RESERVE',
    'wallets.free_label': 'Free',
    'wallets.locked_label': 'Locked',
    'wallets.oversight_title': 'Asset Allocation Oversight',
    'wallets.agg_btc': 'AGGREGATE BTC SPOT EXPOSURE:',
    'wallets.agg_quote': 'AGGREGATE QUOTE CASH EXPOSURE:',

    // Risk & Settings
    'risk.title': 'Risk Manager & Parameters',
    'risk.subtitle': 'Configure safety circuit breakers, minimum spreads, and simulate custom risk levels.',
    'risk.circuit_breakers': 'Active Safety Circuit Breakers',
    'risk.cooldown_status': 'Circuit Breaker Cooldown',
    'risk.cooldown_active': 'ACTIVE COOLDOWN (ENGINE FROZEN)',
    'risk.cooldown_inactive': 'NOMINAL (RUNNING SAFE)',
    'risk.exchanges_exposure': 'Simulated Exposure Caps',
    'risk.global_btc': 'Global BTC Position Cap',
    'risk.global_quote': 'Global Quote Exposure Limit',
    'risk.losses_limit': 'Consecutive Losses Pauser',
    'risk.volatility_breaker': 'Volatility Crash Safeguard',
    'risk.volatility_limit': 'Max Price Divergence (Breaker)',
    'risk.settings_form': 'Configure Simulator Core Parameters',
    'risk.min_net_profit': 'Minimum Executable Net Profit (USD)',
    'risk.max_btc_per_cex': 'Max BTC Position limit per CEX',
    'risk.max_quote_per_cex': 'Max USDT/USD balance per CEX',
    'risk.latency_bps': 'Simulated Latency Drift Buffer (BPS)',
    'risk.slippage_bps': 'Simulated Slippage Safety Cushion (BPS)',
    'risk.trades_per_min': 'Max Trades execution speed (per min)',
    'risk.save_btn': 'Update Engine Parameters',
    'risk.pass_placeholder': 'Enter simulator API secret key...',
    'risk.success_save': 'Simulator configuration updated successfully!',
    'risk.error_save': 'Failed to update configurations. Double check your API secret key.',
    'risk.cooldown_reason': 'Breaker Tripped: Incurred 3 consecutive trade losses from synthetic market slippage.',
    'risk.title_header': 'Risk Oversight Console',
    'risk.subtitle_header': 'Calibrate arbitrage validation parameters, activate system breakers, and manage transaction limits.',
    'risk.system_breaker': 'SYSTEM CIRCUIT BREAKER',
    'risk.engine_health': 'RISK ENGINE SYSTEM HEALTH',
    'risk.circuit_status': 'CIRCUIT STATUS',
    'risk.default_reason': 'All circuit parameters running within safe boundaries. Slippage breakers fully armed.',
    'risk.consecutive_losses': 'CONSECUTIVE LOSSES',
    'risk.cooldown_timer': 'COOLDOWN TIMER',
    'risk.seconds_remaining': 's remaining',
    'risk.inactive': 'INACTIVE',
    'risk.emergency_ops': 'Emergency Operations',
    'risk.rebalance_title': 'Rebalance Reserve Pool',
    'risk.rebalance_desc': 'Flushes trades, opportunities, and logs databases, restoring exchange funds back to default symmetric pools.',
    'risk.resetting_btn': 'Resetting Balances...',
    'risk.reset_balances_btn': 'RESET SIMULATED BALANCES',
    'risk.settings_title': 'Risk Oversight Settings',
    'risk.settings_desc': 'Calibrate mathematical depth-walk parameters and fee/latency hedges.',
    'risk.min_profit_title': 'Minimum Net Profit',
    'risk.min_profit_desc': 'Spread threshold required to trigger simulated orders',
    'risk.max_alloc_title': 'Max Allocation Ceiling',
    'risk.max_alloc_desc': 'Exposure roof capping single transaction sizes',
    'risk.latency_title': 'Latency Safety Buffer',
    'risk.latency_desc': '1 BPS = 0.01%. Expected profit buffer for WebSocket lag rejections',
    'risk.slippage_title': 'Slippage Safety Buffer',
    'risk.slippage_desc': 'Extra safety buffer used to deduct simulated fill prices',
    'risk.saving_msg': 'Saving changes...',
    'risk.success_msg': '✅ Configuration updated and persisted.',
    'risk.error_msg': '❌ Failed to update backend configuration.',
    'risk.save_config_btn': 'Save Configuration Changes',
    'risk.persisting_btn': 'Persisting changes...',
    'risk.dialog_title': 'Reset Simulation State',
    'risk.dialog_desc': 'WARNING: This action will flush all transaction history, opportunities, and log databases, resetting exchange wallet assets back to initial allocations.',
    'risk.dialog_body': 'This execution clears simulated ledger data and restores baseline allocations. This action is irreversible.',
    'risk.cancel': 'Cancel',
    'risk.confirm_reset': 'Confirm Reset',
    'risk.alert_success': '🔄 Simulation database successfully reset to defaults.',
    'risk.alert_error': '❌ Failed to complete database reset. Check logs.',

    // System Health
    'health.title': 'System Feeds & Health',
    'health.subtitle': 'Real-time WebSocket feed status, latencies, CEX ping-pongs, and connection trackers.',
    'health.connection_channels': 'WebSocket Connection Channels',
    'health.venue': 'Exchange Venue',
    'health.stream_url': 'WebSocket Stream Endpoint',
    'health.status_col': 'Channel Status',
    'health.reconnects': 'Reconnects',
    'health.last_msg': 'Last Heartbeat Received',
    'health.system_metrics': 'Simulated Engine Core Metrics',
    'health.uptime': 'Backend Node Uptime',
    'health.api_endpoints': 'REST JSON API Status & Testing',
    'health.title_header': 'System Health Telemetry',
    'health.subtitle_header': 'Track WebSocket streams, connection heartbeats, uptime status, and examine standard audit trails.',
    'health.feed_suffix': 'Feed',
    'health.connected': 'CONNECTED',
    'health.disconnected': 'DISCONNECTED',
    'health.reconnect_counter': 'RECONNECT COUNTER:',
    'health.last_heartbeat': 'LAST HEARTBEAT:',
    'health.no_messages': 'No messages',
    'health.terminal_uptime': 'TERMINAL UPTIME',
    'health.client_socket': 'CLIENT SOCKET CONNECT',
    'health.socket_stable': 'STABLE',
    'health.socket_connecting': 'CONNECTING...',
    'health.logged_events': 'LOGGED EVENTS',
    'health.records_label': 'records',
    'health.detection_latency': 'DETECTION LATENCY',
    'health.audit_trails': 'Platform Audit Trails',
    'health.timestamp_col': 'TIMESTAMP',
    'health.type_col': 'TYPE',
    'health.desc_col': 'EVENT LOG DESCRIPTION MESSAGE',
    'health.no_events': 'No system log events recorded yet.',

    // Platform Docs
    'docs.title_header': 'Platform Documentation',
    'docs.subtitle_header': 'System overview for evaluation, execution logic, and infrastructure design.',
    'docs.flow_market_data': 'Market Data',
    'docs.flow_opportunity': 'Opportunity Engine',
    'docs.flow_execution': 'Execution Simulator',
    'docs.flow_pnl': 'PnL Tracking',
    'docs.sec1_title': 'Cross-Exchange Arbitrage',
    'docs.sec1_p1': 'Aurex is a real-time cross-exchange arbitrage simulator designed to evaluate whether apparent Bitcoin spreads remain executable after depth, fees, and market friction are fully accounted for. Rather than surfacing naive top-of-book discrepancies, the platform models realistic trade sizing, cost-adjusted profitability, and simulated execution across multiple centralized venues.\n\nThe platform monitors live order books across independent exchanges to identify short-lived pricing dislocations for the same asset. A candidate opportunity emerges when the cheapest executable ask on one venue remains below the highest executable bid on another after accounting for execution constraints.',
    'docs.sec2_title': 'Execution Logic',
    'docs.sec2_p1': 'Aurex evaluates opportunities using Level 2 order book depth instead of relying on best bid and best ask alone. This allows the engine to estimate how much size can actually be deployed before slippage compresses or eliminates the available spread.',
    'docs.sec2_seq_title': 'Evaluation sequence',
    'docs.sec2_card_step1': 'Initialize from a conservative test size.',
    'docs.sec2_card_step2': 'Walk sell-side depth on the cheaper venue and buy-side depth on the more expensive venue.',
    'docs.sec2_card_step3': 'Derive weighted average execution prices from consumed liquidity.',
    'docs.sec2_card_step4': 'Apply fees, slippage, and latency protection.',
    'docs.sec2_card_step5': 'Expand position size incrementally until marginal profitability declines.',
    'docs.sec3_title': 'Cost Framework',
    'docs.sec3_p1': 'Raw spread is not treated as profit. Each opportunity is evaluated through a cost framework that incorporates taker fees on both exchanges, transfer or rebalancing assumptions, latency buffers, and the effective slippage implied by real L2 book consumption.',
    'docs.sec3_costs_title': 'Included costs',
    'docs.sec3_li1': 'Taker fees on both exchanges.',
    'docs.sec3_li2': 'Withdrawal or rebalancing fee assumptions.',
    'docs.sec3_li3': 'Latency safety buffer in basis points.',
    'docs.sec3_li4': 'Real slippage from walked L2 liquidity.',
    'docs.sec4_title': 'Architecture',
    'docs.sec4_p1': 'The system is structured as a modular pnpm monorepo separating execution logic, configuration, testing utilities, backend services, and the real-time web terminal.',
    'docs.sec4_workspace_title': 'Workspace components',
    'docs.sec4_li1_desc': 'packages/core — shared domain types and deterministic calculation utilities.',
    'docs.sec4_li2_desc': 'packages/config — exchange metadata, static parameters, and validation schemas.',
    'docs.sec4_li3_desc': 'packages/testing — mock market fixtures and order book fabrication helpers.',
    'docs.sec4_li4_desc': 'apps/bot — backend services, WebSocket ingestion, opportunity scanning, and execution simulation.',
    'docs.sec4_li5_desc': 'apps/web — institutional dashboard for monitoring market state, opportunities, trade history, and portfolio performance.',
    'docs.sec5_title': 'Persistence Layer',
    'docs.sec5_p1': 'Aurex uses a dual persistence strategy to support both frictionless local development and production-grade deployment paths. In the absence of external database credentials, the platform operates in local persistent mode with in-memory state and disk backup; when Supabase credentials are available, persistence is promoted to Postgres-backed storage automatically.',
    'docs.sec5_modes_title': 'Storage modes',
    'docs.sec5_p2_1': 'Local mode: fast in-memory state plus db.json backup persistence across restarts.',
    'docs.sec5_p3': 'Supabase mode: transaction history and state persisted to Postgres tables.',
    
    // New 5-Exchange Comparative Grid translations
    'markets.cex_grid_title': '5-Exchange Spot Tickers',
    'markets.cex_grid_desc': 'Real-time L1 pricing, midpoints, and depth across all five connected exchanges.',
    'markets.spread_matrix_title': 'Cross-Venue 5x5 Net Spread Matrix',
    'markets.spread_matrix_desc': 'Real-time expected net spread net of VIP taker fees, slippage safety buffers, and stablecoin basis costs.',
    'markets.exchange_short': 'Venue',
    'markets.bid_short': 'Bid',
    'markets.ask_short': 'Ask',
    'markets.spread_short': 'Spread',
    'markets.mid_short': 'Mid',
    'markets.depth_short': 'Depth',
    'markets.profitable': 'Profitable',
    'home.terminal_badge': 'Institutional Terminal',
  },
  es: {
    // Navigation Sidebar
    'nav.overview': 'Panel Principal',
    'nav.markets': 'Mercados Comparativos',
    'nav.opportunities': 'Oportunidades en Vivo',
    'nav.trades': 'Operaciones Ejecutadas',
    'nav.wallets': 'Carteras Simuladas',
    'nav.risk': 'Riesgo y Parámetros',
    'nav.health': 'Salud del Sistema',
    'nav.docs': 'Documentación Técnica',
    'nav.status': 'ESTADO DEL NODO:',
    'nav.live': 'EN VIVO',
    
    // Header Ticker
    'ticker.btc_spot': 'SPOT DE BTC:',
    'ticker.detection': 'DETECCIÓN:',
    'ticker.feeds': 'CANALES:',
    'ticker.feeds_suffix': 'activos',
    'ticker.sim_equity': 'PATRIMONIO SIM:',
    'ticker.streaming': '● TRANSMITIENDO',
    'ticker.connecting': '○ CONECTANDO',
    
    // Overview Dashboard
    'overview.title': 'Consola de Arbitraje General',
    'overview.subtitle': 'Motor matemático de spreads y simulador de ejecuciones multi-CEX L2 en tiempo real.',
    'overview.total_profit': 'Beneficio Neto Simulado',
    'overview.win_rate': 'Tasa de Acierto de Simulación',
    'overview.sharpe': 'Ratio de Sharpe',
    'overview.mean_latency': 'Latencia Media',
    'overview.p99_latency': 'Latencia p99',
    'overview.books_sec': 'Rendimiento (Libros/seg)',
    'overview.books_processed': 'Total Libros Evaluados',
    'overview.opps_detected': 'Oportunidades Detectadas',
    'overview.pnl_growth': 'Crecimiento de Patrimonio Simulado (Base 100k USD)',
    'overview.recent_trades': 'Spreads Recientes Capturados',
    'overview.recent_opps': 'Flujo de Spreads en Tiempo Real',
    'overview.no_trades': 'Aún no se han ejecutado operaciones simuladas. Las ventanas de spreads activarán ejecuciones automáticas.',
    'overview.no_opps': 'Esperando datos de libros de órdenes en tiempo real desde los WebSocket de los exchanges...',
    'overview.pnl_chart': 'CRECIMIENTO DE PNL',
    'overview.under_cooldown': 'Disyuntor de Riesgo Activo - Motor en Enfriamiento',
    'overview.monitor_btn': 'Monitorear Libros',
    'overview.risk_btn': 'Ajustar Parámetros',
    'overview.portfolio_equity': 'PATRIMONIO DE CARTERA',
    'overview.initial_reserve': 'Reserva Inicial de 100k USD',
    'overview.sim_net_pnl': 'PNL NETO SIMULADO',
    'overview.after_slippage_fees': 'Después de Deslizamiento y Comisiones',
    'overview.win_rate_label': 'TASA DE ACIERTO',
    'overview.win_rate_sub': 'Control de pérdida por deslizamiento activo',
    'overview.total_trades': 'TOTAL DE OPERACIONES',
    'overview.avg_trade_prefix': 'Prom:',
    'overview.avg_trade_suffix': '/ operación',
    'overview.sharpe_ratio': 'RATIO DE SHARPE',
    'overview.sharpe_sub': 'Tasa libre de riesgo: 0.0%',
    'overview.detection_latency': 'LATENCIA DE DETECCIÓN',
    'overview.books': 'libros',
    'overview.windows': 'ventanas',
    'overview.pnl_chart_title': 'PnL Acumulado',
    'overview.pnl_chart_sub': 'Calculado en cada bloque de ejecución simulado',
    'overview.real_time': 'TIEMPO REAL',
    'overview.sim_context': 'Contexto del Simulador',
    'overview.core_algorithm': 'ALGORITMO CENTRAL:',
    'overview.core_algorithm_desc': 'Clasifica cada par de exchanges dirigidos en 5 plataformas en vivo (Binance, Kraken, Coinbase, OKX, Bybit), calculando el tamaño mediante recorrido L2 y comprobando spreads netos de comisiones VIP, seguridad ante deslizamiento y costes de transferencia — ejecutando entonces la mejor ventana.',
    'overview.sim_rules': 'REGLAS DE SIMULACIÓN:',
    'overview.sim_rules_desc': 'Las operaciones son estrictamente de simulación y no-custodiales. Los balances se restablecen automáticamente al agotarse reservas o alcanzar límites.',
    'overview.last_update': 'Última Actualización:',
    'overview.awaiting_data': 'Esperando datos...',
    'overview.recent_executions': 'Ejecuciones Recientes',
    'overview.trade_ledger_sub': 'Registro diario de operaciones en tiempo real',
    'overview.view_all_btn': 'Ver Todos los Registros →',
    'overview.awaiting_trades': 'Esperando oportunidades de trading... (Ajusta límites de riesgo para activar registros)',
    
    // Home Hero & Intro
    'home.hero_subtitle': 'Simulador de arbitraje de Bitcoin entre exchanges en tiempo real',
    'home.metric_venues': '5 Exchanges Activos',
    'home.metric_books': 'Libros L2 en Vivo',
    'home.metric_execution': 'Ejecución Simulada',
    'home.cta_opportunities': 'Ver Oportunidades en Vivo',
    'home.cta_trades': 'Abrir Historial de Trades',
    'home.inst_bullet1_title': 'Canales de Mercado',
    'home.inst_bullet1_desc': 'Datos de mercado públicos transmitidos en tiempo real desde exchanges activos.',
    'home.inst_bullet2_title': 'Cobertura Matemática',
    'home.inst_bullet2_desc': 'Evaluación de beneficio neto rigurosa tras comisiones VIP, protección de deslizamiento y latencia de red.',
    'home.inst_bullet3_title': 'Seguimiento de Reservas',
    'home.inst_bullet3_desc': 'Motor automatizado de ejecución simulada con seguimiento de wallets, márgenes acumulados y registro de P&L.',

    // Table Headers
    'table.timestamp': 'HORARIO',
    'table.route': 'RUTA',
    'table.volume': 'VOLUMEN',
    'table.buy_price': 'PRECIO COMPRA',
    'table.sell_price': 'PRECIO VENTA',
    'table.gross_pnl': 'P&L BRUTO',
    'table.net_pnl': 'P&L NETO',

    // Comparative Markets
    'markets.title': 'Mercados L2 Comparativos',
    'markets.subtitle': 'Monitoreo de profundidad de libro de órdenes L2 en tiempo real para spreads entre exchanges.',
    'markets.exchange_label': 'Plataforma Exchange',
    'markets.symbol_label': 'Par de Trading',
    'markets.top_bids': 'Mejores Ofertas (Compradores)',
    'markets.top_asks': 'Mejores Demandas (Vendedores)',
    'markets.price': 'Precio (USD)',
    'markets.size': 'Tamaño (BTC)',
    'markets.total': 'Total',
    'markets.no_depth': 'Conectando canal WebSocket de CEX...',
    'markets.depth_visualizer': 'Visualización Gráfica de Profundidad de Libro L2 (BTCUSDT)',
    'markets.route_permutation': 'PERMUTACIÓN DE RUTA',
    'markets.arb_window': 'VENTANA DE ARBITRAJE',
    'markets.no_spread': 'SIN SPREAD',
    'markets.gross_spread': 'SPREAD BRUTO',
    'markets.est_fees': 'TASAS Y COSTES EST.',
    'markets.net_estimate': 'ESTIMACIÓN NETO',
    'markets.unprofitable': 'NO RENTABLE',
    'markets.liquidity_title': 'Análisis de Profundidad de Liquidez',
    'markets.liquidity_sub': 'Cantidad acumulada de ofertas y demandas en torno al precio medio',
    'markets.awaiting_books': 'Esperando actualizaciones en vivo del libro de órdenes por WebSocket...',
    'markets.binance_l2': 'Binance Spot L2 (BTC/USDT)',
    'markets.kraken_l2': 'Kraken Spot L2 (XBT/USD)',
    'markets.binance_l2_desc': 'Tasa Taker VIP: 0.04% | Actualizado cada 100ms',
    'markets.kraken_l2_desc': 'Tasa Taker VIP: 0.10% | Suma de comprobación CRC32 válida',
    'markets.mid_price': 'PRECIO MEDIO',
    'markets.bids_buy': 'Ofertas (Compra)',
    'markets.asks_sell': 'Demandas (Venta)',
    'markets.awaiting_ws': 'Esperando WebSocket...',
    'markets.reference_aggregators': 'Agregadores Externos de Referencia',
    'markets.reference_desc': 'Verifica los spreads en vivo y volumen de liquidez frente a referencias globales.',

    // Live Opportunities
    'opps.title': 'Registro de Spreads de Arbitraje',
    'opps.subtitle': 'Clasificación y registro en tiempo real de cada oportunidad de spread evaluada por el motor.',
    'opps.filter_all': 'Todas las Oportunidades',
    'opps.filter_executed': 'Solo Ejecutadas',
    'opps.filter_skipped': 'Solo Omitidas',
    'opps.col_time': 'Detectada el',
    'opps.col_pair': 'Transición de Venue',
    'opps.col_gross': 'Spread Bruto',
    'opps.col_net': 'Spread Neto',
    'opps.col_volume': 'Volumen Máx',
    'opps.col_profit': 'Beneficio Esp.',
    'opps.col_confidence': 'Conf. (σ)',
    'opps.col_status': 'Estado',
    'opps.col_reason': 'Acción / Razón',
    'opps.executed': 'EJECUTADO',
    'opps.skipped': 'OMITIDO',
    'opps.no_opps': 'No se han registrado oportunidades aún. Escaneando canales de WebSocket...',
    'opps.title_header': 'Oportunidades de Arbitraje en Vivo',
    'opps.subtitle_header': 'Flujo en tiempo real de spreads candidatos evaluados por los bucles del motor.',
    'opps.filter_all_label': 'Todos los Feeds',
    'opps.filter_executed_label': 'Ejecutadas',
    'opps.filter_skipped_label': 'Omitidas',
    'opps.col_ask_buy': 'ASK (COMPRA)',
    'opps.col_bid_sell': 'BID (VENTA)',
    'opps.no_opps_filter': 'No se encontraron oportunidades evaluadas para el filtro activo.',
    'opps.success_reason': 'Dimensionado y Ejecutado con Éxito',
    'opps.table_sub': 'Calculado a partir de snapshots de libros de órdenes',

    // Executed Trades
    'trades.title': 'Registro de Operaciones Ejecutadas',
    'trades.subtitle': 'Ejecuciones simuladas respetando la liquidez L2 recorrida, el deslizamiento spot y las tasas taker.',
    'trades.export': 'Exportar Operaciones (Hoja CSV)',
    'trades.col_time': 'Ejecutado el',
    'trades.col_id': 'ID de Operación/Oportunidad',
    'trades.col_venues': 'Dirección',
    'trades.col_buy_price': 'Precio Compra (recorrido)',
    'trades.col_sell_price': 'Precio Venta (recorrido)',
    'trades.col_volume': 'Volumen (BTC)',
    'trades.col_gross': 'P&L Bruto',
    'trades.col_fees': 'Comisiones Taker Pagadas',
    'trades.col_slippage': 'Deslizamiento Incurrido',
    'trades.col_net': 'Beneficio Neto',
    'trades.no_trades': 'Aún no se han ejecutado operaciones simuladas. Las curvas de beneficio se actualizan al instante al completarse.',
    'trades.title_header': 'Registro de Operaciones Simuladas',
    'trades.subtitle_header': 'Registros de auditoría de todas las ejecuciones de arbitraje entre exchanges completadas por el motor con riesgo mitigado.',
    'trades.export_btn': 'Exportar Trades CSV',
    'trades.accumulated_pnl': 'P&L ACUMULADO SIMULADO',
    'trades.win_rate_count': 'TASA DE ACIERTO / TOTAL',
    'trades.total_fees': 'COMISIONES TAKER TOTALES',
    'trades.slippage_loss': 'PÉRDIDA POR DESLIZAMIENTO',
    'trades.table_title': 'Registro de Ejecución',
    'trades.table_sub': 'Registro en tiempo real de operaciones',
    'trades.no_trades_message': 'Aún no se han ejecutado transacciones. Esperando una ventana entre exchanges que cubra todos los costes; ajusta los límites de riesgo en Parámetros para ampliar la banda de captura.',

    // Simulated Wallets
    'wallets.title': 'Balances de Cuentas y Fondeo',
    'wallets.subtitle': 'Saldos simulados en tiempo real. Los fondos se rebalancean automáticamente al capturar spreads.',
    'wallets.exchange': 'Exchange Venue',
    'wallets.asset': 'Activo',
    'wallets.free': 'Saldo Disponible',
    'wallets.locked': 'Saldo Bloqueado',
    'wallets.total': 'Saldo Total',
    'wallets.value_usd': 'Valor Aprox (USD)',
    'wallets.reset_btn': 'Restablecer Saldos y Cuentas del Simulador',
    'wallets.reset_warning': 'Esto restaurará todas las asignaciones de fondos simulados a sus valores por defecto.',
    'wallets.title_header': 'Reservas de Capital Simuladas',
    'wallets.subtitle_header': 'Supervisa las tenencias de capital, los saldos de activos y la exposición neta cotizada/base por cada exchange activo.',
    'wallets.pool_title': 'Fondo de Saldos',
    'wallets.active_reserve': 'RESERVA ACTIVA',
    'wallets.free_label': 'Disponible',
    'wallets.locked_label': 'Bloqueado',
    'wallets.oversight_title': 'Supervisión de Asignación de Activos',
    'wallets.agg_btc': 'EXPOSICIÓN TOTAL SPOT DE BTC:',
    'wallets.agg_quote': 'EXPOSICIÓN TOTAL DE EFECTIVO COTIZADO:',

    // Risk & Settings
    'risk.title': 'Gestor de Riesgo y Parámetros',
    'risk.subtitle': 'Configura disyuntores de seguridad, spreads mínimos y simula niveles de riesgo avanzados.',
    'risk.circuit_breakers': 'Disyuntores de Seguridad Activos',
    'risk.cooldown_status': 'Estado del Disyuntor',
    'risk.cooldown_active': 'ENFRIAMIENTO ACTIVO (MOTOR PAUSADO)',
    'risk.cooldown_inactive': 'NOMINAL (EJECUCIÓN SEGURA)',
    'risk.exchanges_exposure': 'Límites de Exposición Simulados',
    'risk.global_btc': 'Límite Global de Posición BTC',
    'risk.global_quote': 'Exposición Global Máxima en Dólares',
    'risk.losses_limit': 'Pausa por Pérdidas Consecutivas',
    'risk.volatility_breaker': 'Salvaguarda de Colapso por Volatilidad',
    'risk.volatility_limit': 'Divergencia Máxima de Precios (Corte)',
    'risk.settings_form': 'Configuración de Parámetros del Motor',
    'risk.min_net_profit': 'Beneficio Neto Mínimo Ejecutable (USD)',
    'risk.max_btc_per_cex': 'Posición Máxima BTC por Exchange',
    'risk.max_quote_per_cex': 'Saldo Máximo USDT/USD por Exchange',
    'risk.latency_bps': 'Amortiguador por Desviación de Latencia (BPS)',
    'risk.slippage_bps': 'Colchón de Seguridad para Deslizamiento (BPS)',
    'risk.trades_per_min': 'Velocidad Máxima de Operación (por min)',
    'risk.save_btn': 'Actualizar Parámetros de Simulación',
    'risk.pass_placeholder': 'Introduce la contraseña secreta de API...',
    'risk.success_save': '¡Configuración del motor actualizada correctamente!',
    'risk.error_save': 'Error al actualizar. Comprueba tu clave secreta de API.',
    'risk.cooldown_reason': 'Causa de Disparo: Incurrió en 3 pérdidas consecutivas debido a deslizamientos de mercado sintéticos.',
    'risk.title_header': 'Consola de Supervisión de Riesgos',
    'risk.subtitle_header': 'Calibra los parámetros de validación de arbitraje, activa disyuntores del sistema y gestiona los límites de transacción.',
    'risk.system_breaker': 'DISYUNTOR DE SEGURIDAD',
    'risk.engine_health': 'SALUD DEL MOTOR DE RIESGO',
    'risk.circuit_status': 'ESTADO DEL CIRCUITO',
    'risk.default_reason': 'Todos los parámetros del circuito funcionan dentro de límites seguros. Disyuntores de deslizamiento armados.',
    'risk.consecutive_losses': 'PÉRDIDAS CONSECUTIVAS',
    'risk.cooldown_timer': 'TEMPORIZADOR DE ENFRIAMIENTO',
    'risk.seconds_remaining': 's restantes',
    'risk.inactive': 'INACTIVO',
    'risk.emergency_ops': 'Operaciones de Emergencia',
    'risk.rebalance_title': 'Restablecer Saldos y Cuentas',
    'risk.rebalance_desc': 'Limpia bases de datos de operaciones, oportunidades y registros, restableciendo los fondos a los fondos predeterminados.',
    'risk.resetting_btn': 'Restableciendo Saldos...',
    'risk.reset_balances_btn': 'RESTRABLECER SALDOS SIMULADOS',
    'risk.settings_title': 'Parámetros de Supervisión de Riesgos',
    'risk.settings_desc': 'Calibra los parámetros de recorrido L2 y las coberturas de tarifas/latencia.',
    'risk.min_profit_title': 'Beneficio Neto Mínimo',
    'risk.min_profit_desc': 'Umbral de spread necesario para activar órdenes simuladas',
    'risk.max_alloc_title': 'Techo de Asignación Máxima',
    'risk.max_alloc_desc': 'Límite de exposición máxima para el tamaño de transacciones individuales',
    'risk.latency_title': 'Amortiguador de Latencia',
    'risk.latency_desc': '1 BPS = 0.01%. Margen de beneficio esperado para rechazos por retraso de WebSocket',
    'risk.slippage_title': 'Colchón de Seguridad para Deslizamiento',
    'risk.slippage_desc': 'Colchón de seguridad adicional deducido de los precios de ejecución simulados',
    'risk.saving_msg': 'Guardando cambios...',
    'risk.success_msg': '✅ Configuración actualizada y guardada correctamente.',
    'risk.error_msg': '❌ Error al actualizar la configuración en el servidor.',
    'risk.save_config_btn': 'Guardar Cambios de Configuración',
    'risk.persisting_btn': 'Persistiendo cambios...',
    'risk.dialog_title': 'Restablecer Estado del Simulador',
    'risk.dialog_desc': 'ADVERTENCIA: Esta acción eliminará todo el historial de transacciones, oportunidades y logs, devolviendo los wallets a las asignaciones iniciales.',
    'risk.dialog_body': 'Esta acción borra los datos del libro diario y restaura los balances base de forma irreversible.',
    'risk.cancel': 'Cancelar',
    'risk.confirm_reset': 'Confirmar Restablecimiento',
    'risk.alert_success': '🔄 Base de datos del simulador restablecida con éxito.',
    'risk.alert_error': '❌ Error al restablecer la base de datos. Consulta los logs.',

    // System Health
    'health.title': 'Salud y Canales del Sistema',
    'health.subtitle': 'Estado de conexiones WebSocket, latencias, ping-pongs y reconexión en vivo.',
    'health.connection_channels': 'Canales de Conexión WebSocket',
    'health.venue': 'Exchange Venue',
    'health.stream_url': 'Endpoint WebSocket',
    'health.status_col': 'Estado del Canal',
    'health.reconnects': 'Reconexiones',
    'health.last_msg': 'Último Latido Recibido',
    'health.system_metrics': 'Métricas Centrales del Motor',
    'health.uptime': 'Tiempo de Actividad del Backend',
    'health.api_endpoints': 'Estado y Prueba de la API REST',
    'health.title_header': 'Telemetría de Salud del Sistema',
    'health.subtitle_header': 'Monitorea transmisiones WebSocket, latidos de conexión, estado de uptime e inspecciona registros estándar de auditoría.',
    'health.feed_suffix': 'Canal',
    'health.connected': 'CONECTADO',
    'health.disconnected': 'DESCONECTADO',
    'health.reconnect_counter': 'CONTADOR DE RECONEXIONES:',
    'health.last_heartbeat': 'ÚLTIMO LATIDO:',
    'health.no_messages': 'Sin mensajes',
    'health.terminal_uptime': 'UPTIME DE LA TERMINAL',
    'health.client_socket': 'CONEXIÓN DE SOCKET CLIENTE',
    'health.socket_stable': 'ESTABLE',
    'health.socket_connecting': 'CONECTANDO...',
    'health.logged_events': 'EVENTOS REGISTRADOS',
    'health.records_label': 'registros',
    'health.detection_latency': 'LATENCIA DE DETECCIÓN',
    'health.audit_trails': 'Registros de Auditoría de la Plataforma',
    'health.timestamp_col': 'HORARIO',
    'health.type_col': 'TIPO',
    'health.desc_col': 'MENSAJE DESCRIPTIVO DEL EVENTO',
    'health.no_events': 'Aún no se han registrado eventos en el sistema.',

    // Platform Docs
    'docs.title_header': 'Documentación de la Plataforma',
    'docs.subtitle_header': 'Vista general del sistema para evaluación, lógica de ejecución y diseño de infraestructura.',
    'docs.flow_market_data': 'Datos de Mercado',
    'docs.flow_opportunity': 'Motor de Oportunidades',
    'docs.flow_execution': 'Simulador de Ejecución',
    'docs.flow_pnl': 'Seguimiento de PnL',
    'docs.sec1_title': 'Arbitraje entre Exchanges',
    'docs.sec1_p1': 'Aurex es un simulador de arbitraje entre exchanges en tiempo real diseñado para evaluar si los diferenciales aparentes de Bitcoin siguen siendo ejecutables tras considerar en su totalidad la profundidad, comisiones y fricción del mercado. En lugar de mostrar discrepancias simples de tope de libro, la plataforma modela el tamaño de operación realista, la rentabilidad ajustada por costes y la ejecución simulada a través de múltiples mercados centralizados.\n\nLa plataforma monitorea libros de órdenes en vivo en exchanges independientes para identificar dislocaciones de precios de corta duración para el mismo activo. Surge una oportunidad candidata cuando la oferta de venta ejecutable más barata en una plataforma permanece por debajo de la demanda de compra ejecutable más alta en otra tras contabilizar las restricciones de ejecución.',
    'docs.sec2_title': 'Lógica de Ejecución',
    'docs.sec2_p1': 'Aurex evalúa las oportunidades utilizando la profundidad del libro de órdenes de Nivel 2 en lugar de confiar únicamente en la mejor oferta de compra y venta. Esto permite al motor estimar cuánto volumen se puede desplegar realmente antes de que el deslizamiento reduzca o elimine el diferencial disponible.',
    'docs.sec2_seq_title': 'Secuencia de evaluación',
    'docs.sec2_card_step1': 'Inicializar desde un tamaño de prueba conservador.',
    'docs.sec2_card_step2': 'Recorrer la profundidad de venta en la plataforma barata y la profundidad de compra en la plataforma cara.',
    'docs.sec2_card_step3': 'Derivar precios promedio ponderados de ejecución a partir de la liquidez consumida.',
    'docs.sec2_card_step4': 'Aplicar comisiones, deslizamiento y protección de latencia.',
    'docs.sec2_card_step5': 'Expandir el tamaño de la posición de forma incremental hasta que el beneficio marginal disminuya.',
    'docs.sec3_title': 'Marco de Costes',
    'docs.sec3_p1': 'El spread bruto no se trata como beneficio puro. Cada oportunidad se evalúa a través de un marco de costes detallado que incorpora comisiones de taker en ambos exchanges, asunciones de transferencia o rebalanceo, amortiguadores de latencia y el deslizamiento real implicado por el consumo de libros L2.',
    'docs.sec3_costs_title': 'Costes incluidos',
    'docs.sec3_li1': 'Comisiones Taker en ambos exchanges.',
    'docs.sec3_li2': 'Asunciones de tarifas de retiro o rebalanceo de cartera.',
    'docs.sec3_li3': 'Amortiguador de seguridad por latencia en puntos básicos (BPS).',
    'docs.sec3_li4': 'Deslizamiento real de la liquidez recorrida L2.',
    'docs.sec4_title': 'Arquitectura',
    'docs.sec4_p1': 'El sistema está estructurado como un monorepositorio modular pnpm que separa la lógica de ejecución, la configuración, las utilidades de prueba, los servicios del backend y la terminal web en tiempo real.',
    'docs.sec4_workspace_title': 'Componentes del espacio de trabajo',
    'docs.sec4_li1_desc': 'packages/core — tipos de dominio compartidos y utilidades de cálculo deterministas.',
    'docs.sec4_li2_desc': 'packages/config — metadatos del exchange, parámetros estáticos y esquemas de validación.',
    'docs.sec4_li3_desc': 'packages/testing — fixtures de mercado simulados y asistentes para la fabricación de libros de órdenes.',
    'docs.sec4_li4_desc': 'apps/bot — servicios de backend, ingesta de WebSocket, escaneo de oportunidades y simulación de ejecución.',
    'docs.sec4_li5_desc': 'apps/web — panel institucional para el monitoreo del estado del mercado, oportunidades, historial de trades y rendimiento del portfolio.',
    'docs.sec5_title': 'Capa de Persistencia',
    'docs.sec5_p1': 'Aurex utiliza una estrategia de persistencia dual para dar soporte tanto a un desarrollo local sin fricciones como a rutas de despliegue de nivel de producción. Ante la ausencia de credenciales de bases de datos externas, la plataforma opera en modo persistente local con estado en memoria y copias de seguridad en disco; cuando las credenciales de Supabase están disponibles, la persistencia se promueve automáticamente a almacenamiento PostgreSQL.',
    'docs.sec5_modes_title': 'Modos de almacenamiento',
    'docs.sec5_p2_1': 'Modo Local: estado rápido en memoria y persistencia de copias de seguridad en el archivo db.json.',
    'docs.sec5_p3': 'Modo Supabase: historial de transacciones y estado persistidos directamente en tablas PostgreSQL de Supabase.',
    
    // New 5-Exchange Comparative Grid translations
    'markets.cex_grid_title': 'Precios Spot de los 5 Exchanges',
    'markets.cex_grid_desc': 'Precios L1 en tiempo real, puntos medios y profundidad en las cinco plataformas conectadas.',
    'markets.spread_matrix_title': 'Matriz de Spreads Netos 5x5 entre Exchanges',
    'markets.spread_matrix_desc': 'Spreads netos esperados en tiempo real descontando comisiones taker VIP, colchón de deslizamiento y comisiones de paridad de establecoin.',
    'markets.exchange_short': 'Exchange',
    'markets.bid_short': 'Bid',
    'markets.ask_short': 'Ask',
    'markets.spread_short': 'Spread',
    'markets.mid_short': 'Medio',
    'markets.depth_short': 'Profundidad',
    'markets.profitable': 'Rentable',
    'home.terminal_badge': 'Terminal Institucional',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('en');

  // Load language preference from localStorage on mount
  useEffect(() => {
    const saved = localStorage.getItem('aurex_lang');
    if (saved === 'en' || saved === 'es') {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('aurex_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
