'use client';

import Link from 'next/link';
import React from 'react';

import { Button } from '@/components/ui/button';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';

import { useLanguage } from '../LanguageContext';

export default function PrivacyPage() {
  const { language } = useLanguage();

  return (
    <div className="space-y-8 animate-fadeIn max-w-[1000px] mx-auto pb-10">
      {/* HEADER */}
      <div className="pb-6 border-b border-white/5 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-white sm:text-3xl font-mono uppercase">
            {language === 'es' ? 'POLÍTICA DE PRIVACIDAD' : 'PRIVACY POLICY'}
          </h2>
          <p className="mt-2 text-sm text-slate-400 font-sans">
            {language === 'es' ? 'Última actualización: 31 de mayo de 2026' : 'Last updated: May 31, 2026'}
          </p>
        </div>
        <Link href="/" passHref legacyBehavior>
          <Button variant="outline" size="sm" className="border-white/10 bg-white/5 hover:bg-white/10 text-white font-mono text-xs self-start md:self-center">
            &larr; {language === 'es' ? 'Volver al Panel' : 'Back to Dashboard'}
          </Button>
        </Link>
      </div>

      {/* CONTENT CARD */}
      <Card className="border border-white/5 bg-slate-950/20 backdrop-blur-md">
        <CardHeader className="border-b border-white/5 bg-slate-950/10 p-6">
          <CardTitle className="text-sm font-mono font-bold text-white uppercase tracking-wider">
            {language === 'es' ? 'PRIVACIDAD EN AUREX' : 'AUREX PRIVACY'}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6 pt-6 text-sm text-slate-300 leading-relaxed font-sans p-6 md:p-8">
          <p className="font-semibold text-slate-200">
            {language === 'es'
              ? 'Aurex es un simulador de arbitraje de Bitcoin entre exchanges, sin custodia y solo para fines educativos. Está diseñado para recopilar la menor cantidad de datos posible: no requiere cuentas de usuario, no solicita información personal y no maneja fondos ni claves.'
              : 'Aurex is a non-custodial, education-only Bitcoin cross-exchange arbitrage simulator. It is designed to collect as little data as possible: it requires no user accounts, requests no personal information, and handles no funds or keys.'}
          </p>

          <p className="text-xs text-amber-500/80 bg-amber-500/5 px-3 py-2 rounded border border-amber-500/10 font-mono tracking-wide uppercase inline-block">
            {language === 'es' ? 'Al usar la Plataforma, aceptas esta política.' : 'By using the Platform, you agree to this policy.'}
          </p>

          <div className="space-y-6 mt-8">
            <section className="space-y-2">
              <h3 className="font-mono text-sm font-bold text-white uppercase tracking-wider border-b border-white/5 pb-1.5">
                1. {language === 'es' ? 'Información que NO recopilamos' : 'Information We Do NOT Collect'}
              </h3>
              <ul className="list-disc list-inside space-y-1.5 pl-2 text-slate-300">
                <li>{language === 'es' ? 'No hay registro ni cuentas de usuario; no pedimos nombre, email ni teléfono.' : 'There is no sign-up or user account; we do not ask for your name, email, or phone number.'}</li>
                <li>{language === 'es' ? 'No recopilamos ni almacenamos claves privadas, frases semilla ni credenciales de exchange.' : 'We do not collect or store private keys, seed phrases, or exchange credentials.'}</li>
                <li>{language === 'es' ? 'No recopilamos datos sensibles ni información personal identificable (PII).' : 'We do not collect sensitive data or personally identifiable information (PII).'}</li>
              </ul>
            </section>

            <section className="space-y-2">
              <h3 className="font-mono text-sm font-bold text-white uppercase tracking-wider border-b border-white/5 pb-1.5">
                2. {language === 'es' ? 'Datos que sí procesamos' : 'Data We Do Process'}
              </h3>
              <ul className="list-disc list-inside space-y-1.5 pl-2 text-slate-300">
                <li><strong className="text-white">{language === 'es' ? 'Datos de mercado públicos:' : 'Public market data:'}</strong> {language === 'es' ? 'libros de órdenes y precios transmitidos por exchanges de terceros. No contienen información personal.' : 'order books and prices streamed from third-party exchanges. These contain no personal information.'}</li>
                <li><strong className="text-white">{language === 'es' ? 'Estado simulado:' : 'Simulated state:'}</strong> {language === 'es' ? 'operaciones, oportunidades, balances y P&L generados por el motor. Todo es sintético y no está vinculado a ninguna persona.' : 'trades, opportunities, balances, and P&L generated by the engine. All of it is synthetic and tied to no individual.'}</li>
                <li><strong className="text-white">{language === 'es' ? 'Registros técnicos:' : 'Technical logs:'}</strong> {language === 'es' ? 'nuestros proveedores de hosting pueden registrar datos estándar de solicitud (dirección IP, agente de usuario) por seguridad y operación.' : 'our hosting providers may log standard request data (IP address, user agent) for security and operations.'}</li>
              </ul>
            </section>

            <section className="space-y-2">
              <h3 className="font-mono text-sm font-bold text-white uppercase tracking-wider border-b border-white/5 pb-1.5">
                3. {language === 'es' ? 'Cookies y almacenamiento local' : 'Cookies and Local Storage'}
              </h3>
              <p className="text-slate-300">
                {language === 'es'
                  ? 'No usamos cookies de seguimiento ni publicidad. La Plataforma solo guarda tu preferencia de idioma en el almacenamiento local de tu navegador (clave aurex_lang).'
                  : 'We do not use tracking or advertising cookies. The Platform only stores your language preference in your browser’s local storage (the aurex_lang key).'}
              </p>
              <p className="text-slate-400 text-xs">
                {language === 'es'
                  ? 'Puedes borrar ese valor en cualquier momento desde la configuración de tu navegador, sin afectar el funcionamiento.'
                  : 'You can clear that value at any time from your browser settings without affecting functionality.'}
              </p>
            </section>

            <section className="space-y-2">
              <h3 className="font-mono text-sm font-bold text-white uppercase tracking-wider border-b border-white/5 pb-1.5">
                4. {language === 'es' ? 'Proveedores de servicios' : 'Service Providers'}
              </h3>
              <p className="text-slate-300">
                {language === 'es'
                  ? 'La Plataforma se apoya en infraestructura de terceros para funcionar:'
                  : 'The Platform relies on third-party infrastructure to operate:'}
              </p>
              <ul className="list-disc list-inside space-y-1 pl-2 text-slate-300">
                <li>{language === 'es' ? 'Hosting y despliegue (p. ej. Vercel y Fly.io).' : 'Hosting and deployment (e.g. Vercel and Fly.io).'}</li>
                <li>{language === 'es' ? 'Base de datos para el estado simulado (p. ej. Supabase Postgres).' : 'A database for simulated state (e.g. Supabase Postgres).'}</li>
                <li>{language === 'es' ? 'Feeds públicos de datos de mercado de los exchanges conectados.' : 'Public market-data feeds from the connected exchanges.'}</li>
              </ul>
              <p className="text-slate-400 text-xs pt-1">
                {language === 'es'
                  ? 'Estos proveedores procesan únicamente datos técnicos u operativos conforme a sus propias políticas.'
                  : 'These providers process only technical or operational data in accordance with their own policies.'}
              </p>
            </section>

            <section className="space-y-2">
              <h3 className="font-mono text-sm font-bold text-white uppercase tracking-wider border-b border-white/5 pb-1.5">
                5. {language === 'es' ? 'Seguridad y retención' : 'Security and Retention'}
              </h3>
              <p className="text-slate-300">
                {language === 'es'
                  ? 'Las conexiones usan cifrado en tránsito (HTTPS/WSS). Dado que el estado almacenado es sintético, el reinicio o la limpieza del simulador elimina dichos registros.'
                  : 'Connections use encryption in transit (HTTPS/WSS). Because the stored state is synthetic, resetting or clearing the simulator removes those records.'}
              </p>
            </section>

            <section className="space-y-2">
              <h3 className="font-mono text-sm font-bold text-white uppercase tracking-wider border-b border-white/5 pb-1.5">
                6. {language === 'es' ? 'Enlaces a terceros' : 'Third-Party Links'}
              </h3>
              <p className="text-slate-300">
                {language === 'es'
                  ? 'La Plataforma puede enlazar a sitios externos (p. ej. exchanges o agregadores de referencia). No somos responsables de sus prácticas de privacidad.'
                  : 'The Platform may link to external sites (e.g. exchanges or reference aggregators). We are not responsible for their privacy practices.'}
              </p>
            </section>

            <section className="space-y-2">
              <h3 className="font-mono text-sm font-bold text-white uppercase tracking-wider border-b border-white/5 pb-1.5">
                7. {language === 'es' ? 'Cambios a esta política' : 'Changes to This Policy'}
              </h3>
              <p className="text-slate-300">
                {language === 'es'
                  ? 'Podemos actualizar esta política. Los cambios significativos se publicarán en esta misma página con una nueva fecha de actualización.'
                  : 'We may update this policy. Significant changes will be posted on this page with a new "last updated" date.'}
              </p>
            </section>

            <section className="space-y-2">
              <h3 className="font-mono text-sm font-bold text-white uppercase tracking-wider border-b border-white/5 pb-1.5">
                8. {language === 'es' ? 'Contacto' : 'Contact'}
              </h3>
              <p className="text-slate-300">
                {language === 'es'
                  ? 'Para preguntas sobre privacidad, abre un issue en el repositorio del proyecto.'
                  : 'For privacy questions, open an issue in the project repository.'}
              </p>
            </section>
          </div>

          <div className="border-t border-white/5 pt-6 text-center text-xs font-mono text-slate-500">
            {language === 'es'
              ? 'Aurex — entorno estrictamente simulado. Sin trading real.'
              : 'Aurex — strictly simulated environment. No real trading.'}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
